[manjaro-tools] code formatting

diff --git a/bin/buildiso.in b/bin/buildiso.in
--- a/bin/buildiso.in
+++ b/bin/buildiso.in
@@ -21,101 +21,101 @@ SYSCONFDIR='@sysconfdir@'
 [[ -r ${LIBDIR}/util-iso.sh ]] && source ${LIBDIR}/util-iso.sh
 
 display_settings(){
-    msg "manjaro-tools"
-    msg2 "version: ${version}"
+	msg "manjaro-tools"
+	msg2 "version: ${version}"
 
-    if [[ -f ${USER_CONFIG}/manjaro-tools.conf ]]; then
-	msg2 "user_config: ${USER_CONFIG}/manjaro-tools.conf"
-    else
-	msg2 "manjaro_tools_conf: ${manjaro_tools_conf}"
-    fi
+	if [[ -f ${USER_CONFIG}/manjaro-tools.conf ]]; then
+		msg2 "user_config: ${USER_CONFIG}/manjaro-tools.conf"
+	else
+		msg2 "manjaro_tools_conf: ${manjaro_tools_conf}"
+	fi
 
-    msg "PROFILE:"
-    msg2 "buildsets: $(load_sets ${sets_dir_iso})"
-    msg2 "buildset_iso: ${buildset_iso}"
-    msg2 "is_buildset: ${is_buildset}"
+	msg "PROFILE:"
+	msg2 "buildsets: $(load_sets ${sets_dir_iso})"
+	msg2 "buildset_iso: ${buildset_iso}"
+	msg2 "is_buildset: ${is_buildset}"
 
-    msg "OPTIONS:"
-    msg2 "arch: ${arch}"
-    msg2 "branch: ${branch}"
-    msg2 "chroots_iso: ${chroots_iso}"
+	msg "OPTIONS:"
+	msg2 "arch: ${arch}"
+	msg2 "branch: ${branch}"
+	msg2 "chroots_iso: ${chroots_iso}"
 
-    msg "ARGS:"
-    msg2 "clean_first: ${clean_first}"
-    msg2 "clean_cache_xorg: ${clean_cache_xorg}"
-    msg2 "clean_cache_lng: ${clean_cache_lng}"
-    msg2 "clean_cache_iso: ${clean_cache_iso}"
-    msg2 "images_only: ${images_only}"
-    msg2 "iso_only: ${iso_only}"
+	msg "ARGS:"
+	msg2 "clean_first: ${clean_first}"
+	msg2 "clean_cache_xorg: ${clean_cache_xorg}"
+	msg2 "clean_cache_lng: ${clean_cache_lng}"
+	msg2 "clean_cache_iso: ${clean_cache_iso}"
+	msg2 "images_only: ${images_only}"
+	msg2 "iso_only: ${iso_only}"
 
-    msg "PATHS:"
-    msg2 "sets_dir_iso: ${sets_dir_iso}"
-    msg2 "cache_dir_iso: ${cache_dir_iso}"
-    msg2 "cache_dir_xorg: ${cache_dir_xorg}"
-    msg2 "cache_dir_lng: ${cache_dir_lng}"
+	msg "PATHS:"
+	msg2 "sets_dir_iso: ${sets_dir_iso}"
+	msg2 "cache_dir_iso: ${cache_dir_iso}"
+	msg2 "cache_dir_xorg: ${cache_dir_xorg}"
+	msg2 "cache_dir_lng: ${cache_dir_lng}"
 
-    msg "IMAGES SETTINGS:"
-    msg2 "manjaro_kernel: ${manjaro_kernel}"
-    msg2 "manjaro_version: ${manjaro_version}"
-    msg2 "plymouth_theme: ${plymouth_theme}"
+	msg "IMAGES SETTINGS:"
+	msg2 "manjaro_kernel: ${manjaro_kernel}"
+	msg2 "manjaro_version: ${manjaro_version}"
+	msg2 "plymouth_theme: ${plymouth_theme}"
 
-    msg "ISO SETTINGS:"
-    msg2 "iso_label: ${iso_label}"
-    msg2 "iso_version: ${iso_version}"
-    msg2 "code_name: ${code_name}"
+	msg "ISO SETTINGS:"
+	msg2 "iso_label: ${iso_label}"
+	msg2 "iso_version: ${iso_version}"
+	msg2 "code_name: ${code_name}"
 #     msg2 "manjaroiso: ${manjaroiso}"
 #     msg2 "img_name: ${img_name}"
 #     msg2 "install_dir: ${install_dir}"
 #     msg2 "compression: ${compression}"
 #     msg2 "checksum_mode: ${checksum_mode}"
 
-    msg "LIVECD:"
-    msg2 "username: ${username}"
-    msg2 "password: ${password}"
-    msg2 "addgroups: ${addgroups}"
-    msg2 "hostname: ${hostname}"
+	msg "LIVECD:"
+	msg2 "username: ${username}"
+	msg2 "password: ${password}"
+	msg2 "addgroups: ${addgroups}"
+	msg2 "hostname: ${hostname}"
 
-    msg "BUILD QUEUE:"
-    if ${is_buildset};then
-	local list=$(cat ${sets_dir_iso}/${buildset_iso}.set)
-	for item in ${list[@]}; do
-            check_profile "$item"
-	    cd $item
-	    load_profile "$item"
-	    msg2 "initsys: ${initsys}"
-	    msg2 "displaymanager: ${displaymanager}"
-	    msg2 "is_plymouth: ${is_plymouth}"
-	    msg2 "pacman_conf: ${pacman_conf}"
-	    msg2 "work_dir: ${work_dir}"
-	    msg2 "iso_file: ${iso_file}"
-	    if [[ ${initsys} == 'systemd' ]];then
-		msg2 "start_systemd: ${start_systemd[*]}"
-		msg2 "start_systemd_live: ${start_systemd_live[*]}"
-	    else
-		msg2 "start_openrc: ${start_openrc[*]}"
-		msg2 "start_openrc_live: ${start_openrc_live[*]}"
-	    fi
-	    cd ..
-	done
-    else
-        check_profile "${buildset_iso}"
-	cd ${buildset_iso}
-	load_profile "${buildset_iso}"
-	msg2 "initsys: ${initsys}"
-	msg2 "displaymanager: ${displaymanager}"
-	msg2 "is_plymouth: ${is_plymouth}"
-	msg2 "pacman_conf: ${pacman_conf}"
-	msg2 "work_dir: ${work_dir}"
-	msg2 "iso_file: ${iso_file}"
-	if [[ ${initsys} == 'systemd' ]];then
-	    msg2 "start_systemd: ${start_systemd[*]}"
-	    msg2 "start_systemd_live: ${start_systemd_live[*]}"
+	msg "BUILD QUEUE:"
+	if ${is_buildset};then
+		local list=$(cat ${sets_dir_iso}/${buildset_iso}.set)
+		for item in ${list[@]}; do
+			check_profile "$item"
+			cd $item
+				load_profile "$item"
+				msg2 "initsys: ${initsys}"
+				msg2 "displaymanager: ${displaymanager}"
+				msg2 "is_plymouth: ${is_plymouth}"
+				msg2 "pacman_conf: ${pacman_conf}"
+				msg2 "work_dir: ${work_dir}"
+				msg2 "iso_file: ${iso_file}"
+				if [[ ${initsys} == 'systemd' ]];then
+					msg2 "start_systemd: ${start_systemd[*]}"
+					msg2 "start_systemd_live: ${start_systemd_live[*]}"
+				else
+					msg2 "start_openrc: ${start_openrc[*]}"
+					msg2 "start_openrc_live: ${start_openrc_live[*]}"
+				fi
+			cd ..
+		done
 	else
-	    msg2 "start_openrc: ${start_openrc[*]}"
-	    msg2 "start_openrc_live: ${start_openrc_live[*]}"
+		check_profile "${buildset_iso}"
+		cd ${buildset_iso}
+			load_profile "${buildset_iso}"
+			msg2 "initsys: ${initsys}"
+			msg2 "displaymanager: ${displaymanager}"
+			msg2 "is_plymouth: ${is_plymouth}"
+			msg2 "pacman_conf: ${pacman_conf}"
+			msg2 "work_dir: ${work_dir}"
+			msg2 "iso_file: ${iso_file}"
+			if [[ ${initsys} == 'systemd' ]];then
+				msg2 "start_systemd: ${start_systemd[*]}"
+				msg2 "start_systemd_live: ${start_systemd_live[*]}"
+			else
+				msg2 "start_openrc: ${start_openrc[*]}"
+				msg2 "start_openrc_live: ${start_openrc_live[*]}"
+			fi
+		cd ..
 	fi
-	cd ..
-    fi
 }
 
 load_user_info
@@ -135,24 +135,24 @@ iso_only=false
 pacman_conf_arch='default'
 
 usage() {
-    echo "Usage: ${0##*/} [options]"
-    echo "    -p <profile>       Buildset or profile [default: ${buildset_iso}]"
-    echo "    -a <arch>          Arch [default: ${arch}]"
-    echo "    -b <branch>        Branch [default: ${branch}]"
-    echo '    -r <dir>           Chroots directory'
-    echo "                       [default: ${chroots_iso}]"
-    echo '    -w                 Disable clean iso cache'
-    echo '    -c                 Disable clean work dir'
-    echo '    -x                 Disable clean xorg cache'
-    echo '    -l                 Disable clean lng cache'
-    echo '    -i                 Build images only'
-    echo '    -s                 Generate iso only'
-    echo '                       Requires pre built images (-i)'
-    echo '    -q                 Query settings and pretend build'
-    echo '    -h                 This help'
-    echo ''
-    echo ''
-    exit $1
+	echo "Usage: ${0##*/} [options]"
+	echo "    -p <profile>       Buildset or profile [default: ${buildset_iso}]"
+	echo "    -a <arch>          Arch [default: ${arch}]"
+	echo "    -b <branch>        Branch [default: ${branch}]"
+	echo '    -r <dir>           Chroots directory'
+	echo "                       [default: ${chroots_iso}]"
+	echo '    -w                 Disable clean iso cache'
+	echo '    -c                 Disable clean work dir'
+	echo '    -x                 Disable clean xorg cache'
+	echo '    -l                 Disable clean lng cache'
+	echo '    -i                 Build images only'
+	echo '    -s                 Generate iso only'
+	echo '                       Requires pre built images (-i)'
+	echo '    -q                 Query settings and pretend build'
+	echo '    -h                 This help'
+	echo ''
+	echo ''
+	exit $1
 }
 
 orig_argv=("$@")
@@ -160,27 +160,27 @@ orig_argv=("$@")
 opts='p:a:b:r:cxlisqwh'
 
 while getopts "${opts}" arg; do
-    case "${arg}" in
-	p) buildset_iso="$OPTARG" ;;
-	a) arch="$OPTARG" ;;
-	b) branch="$OPTARG" ;;
-	r) chroots_iso="$OPTARG" ;;
-	c) clean_first=false ;;
-	w) clean_cache_iso=false;;
-	x) clean_cache_xorg=false ;;
-	l) clean_cache_lng=false ;;
-	i) images_only=true ;;
-	s) iso_only=true ;;
-	q) pretend=true ;;
-	h|?) usage 0 ;;
-        *) echo "invalid argument '${arg}'"; usage 1 ;;
-    esac
+	case "${arg}" in
+		p) buildset_iso="$OPTARG" ;;
+		a) arch="$OPTARG" ;;
+		b) branch="$OPTARG" ;;
+		r) chroots_iso="$OPTARG" ;;
+		c) clean_first=false ;;
+		w) clean_cache_iso=false;;
+		x) clean_cache_xorg=false ;;
+		l) clean_cache_lng=false ;;
+		i) images_only=true ;;
+		s) iso_only=true ;;
+		q) pretend=true ;;
+		h|?) usage 0 ;;
+		*) echo "invalid argument '${arg}'"; usage 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 
 if [[ "$arch" == 'x86_64' ]]; then
-    pacman_conf_arch='multilib'
+	pacman_conf_arch='multilib'
 fi
 
 cache_dir_lng="${cache_dir}/lng/${arch}"
diff --git a/bin/buildpkg.in b/bin/buildpkg.in
--- a/bin/buildpkg.in
+++ b/bin/buildpkg.in
@@ -22,71 +22,71 @@ SYSCONFDIR='@sysconfdir@'
 [[ -r ${LIBDIR}/util-pkg.sh ]] && source ${LIBDIR}/util-pkg.sh
 
 display_settings(){
-    msg "manjaro-tools"
-    msg2 "version: ${version}"
+	msg "manjaro-tools"
+	msg2 "version: ${version}"
 
-    if [[ -f ${USER_CONFIG}/manjaro-tools.conf ]]; then
-	msg2 "user_config: ${USER_CONFIG}/manjaro-tools.conf"
-    else
-	msg2 "manjaro_tools_conf: ${manjaro_tools_conf}"
-    fi
-
-    msg "PROFILE:"
-    msg2 "buildsets: $(load_sets ${sets_dir_pkg})"
-    msg2 "buildset_pkg: ${buildset_pkg}"
-    msg2 "is_buildset: ${is_buildset}"
-
-    msg "OPTIONS:"
-    msg2 "arch: ${arch}"
-    msg2 "branch: ${branch}"
-    msg2 "chroots_pkg: ${chroots_pkg}"
-
-    msg "ARGS:"
-    msg2 "clean_first: ${clean_first}"
-    msg2 "wipe_clean: ${wipe_clean}"
-    msg2 "namcap: ${namcap}"
-    msg2 "sign: ${sign}"
-    msg2 "makepkg_args: ${makepkg_args[*]}"
-
-    msg "PATHS:"
-    msg2 "work_dir: ${work_dir}"
-    msg2 "sets_dir_pkg: ${sets_dir_pkg}"
-    msg2 "cache_dir_pkg: ${cache_dir_pkg}"
-    msg2 "build_mirror: ${build_mirror}/${branch}"
-
-    msg "BLACKLIST:"
-    msg2 "blacklist_trigger: ${blacklist_trigger[*]}"
-    msg2 "blacklist: ${blacklist[*]}"
-
-    if ${clean_first};then
-	msg "PKG:"
-	msg2 "base_packages: ${base_packages[*]}"
-    fi
-
-    msg "BUILD QUEUE:"
-    if ${is_buildset};then
-	local list=$(cat ${sets_dir_pkg}/${buildset_pkg}.set)
-	for item in ${list[@]}; do
-	    msg2 "$item"
-	done
-    else
-	for arg in "${makepkg_args[@]}"; do
-	    case ${arg} in
-		--pkg) continue ;;
-		-*) continue ;;
-		*) local split_arg=${arg} ;;
-	    esac
-	done
-	if [[ -n ${split_arg} ]]; then
-	    local IFS=','
-	    for item in ${split_arg}; do
-		msg2 "$item"
-	    done
-	    unset IFS
+	if [[ -f ${USER_CONFIG}/manjaro-tools.conf ]]; then
+		msg2 "user_config: ${USER_CONFIG}/manjaro-tools.conf"
 	else
-	    msg2 "${buildset_pkg}"
+		msg2 "manjaro_tools_conf: ${manjaro_tools_conf}"
 	fi
-    fi
+
+	msg "PROFILE:"
+	msg2 "buildsets: $(load_sets ${sets_dir_pkg})"
+	msg2 "buildset_pkg: ${buildset_pkg}"
+	msg2 "is_buildset: ${is_buildset}"
+
+	msg "OPTIONS:"
+	msg2 "arch: ${arch}"
+	msg2 "branch: ${branch}"
+	msg2 "chroots_pkg: ${chroots_pkg}"
+
+	msg "ARGS:"
+	msg2 "clean_first: ${clean_first}"
+	msg2 "wipe_clean: ${wipe_clean}"
+	msg2 "namcap: ${namcap}"
+	msg2 "sign: ${sign}"
+	msg2 "makepkg_args: ${makepkg_args[*]}"
+
+	msg "PATHS:"
+	msg2 "work_dir: ${work_dir}"
+	msg2 "sets_dir_pkg: ${sets_dir_pkg}"
+	msg2 "cache_dir_pkg: ${cache_dir_pkg}"
+	msg2 "build_mirror: ${build_mirror}/${branch}"
+
+	msg "BLACKLIST:"
+	msg2 "blacklist_trigger: ${blacklist_trigger[*]}"
+	msg2 "blacklist: ${blacklist[*]}"
+
+	if ${clean_first};then
+		msg "PKG:"
+		msg2 "base_packages: ${base_packages[*]}"
+	fi
+
+	msg "BUILD QUEUE:"
+	if ${is_buildset};then
+		local list=$(cat ${sets_dir_pkg}/${buildset_pkg}.set)
+		for item in ${list[@]}; do
+			msg2 "$item"
+		done
+	else
+		for arg in "${makepkg_args[@]}"; do
+			case ${arg} in
+				--pkg) continue ;;
+				-*) continue ;;
+				*) local split_arg=${arg} ;;
+			esac
+		done
+		if [[ -n ${split_arg} ]]; then
+			local IFS=','
+			for item in ${split_arg}; do
+				msg2 "$item"
+			done
+			unset IFS
+		else
+			msg2 "${buildset_pkg}"
+		fi
+	fi
 }
 
 load_user_info
@@ -108,21 +108,21 @@ is_buildset=false
 sign=false
 
 usage() {
-    echo "Usage: ${0##*/} [options] [--] [makepkg args]"
-    echo "    -p <pkg>           Buildset or pkg [default: ${buildset_pkg}]"
-    echo "    -a <arch>          Arch [default: ${arch}]"
-    echo "    -b <branch>        Branch [default: ${branch}]"
-    echo '    -r <dir>           Chroots directory'
-    echo "                       [default: ${chroots_pkg}]"
-    echo '    -c                 Recreate chroot'
-    echo '    -w                 Clean up cache and sources'
-    echo '    -n                 Install and run namcap check'
-    echo '    -s                 Sign packages'
-    echo '    -q                 Query settings and pretend build'
-    echo '    -h                 This help'
-    echo ''
-    echo ''
-    exit $1
+	echo "Usage: ${0##*/} [options] [--] [makepkg args]"
+	echo "    -p <pkg>           Buildset or pkg [default: ${buildset_pkg}]"
+	echo "    -a <arch>          Arch [default: ${arch}]"
+	echo "    -b <branch>        Branch [default: ${branch}]"
+	echo '    -r <dir>           Chroots directory'
+	echo "                       [default: ${chroots_pkg}]"
+	echo '    -c                 Recreate chroot'
+	echo '    -w                 Clean up cache and sources'
+	echo '    -n                 Install and run namcap check'
+	echo '    -s                 Sign packages'
+	echo '    -q                 Query settings and pretend build'
+	echo '    -h                 This help'
+	echo ''
+	echo ''
+	exit $1
 }
 
 orig_argv=("$@")
@@ -130,32 +130,32 @@ orig_argv=("$@")
 opts='p:a:b:r:cwnsqh'
 
 while getopts "${opts}" arg; do
-    case "${arg}" in
-	p) buildset_pkg="$OPTARG" ;;
-	a) arch="$OPTARG" ;;
-	b) branch="$OPTARG" ;;
-	r) chroots_pkg="$OPTARG" ;;
-	c) clean_first=true; mkchroot_args+=(-L) ;;
-	w) wipe_clean=true ;;
-	n) namcap=true; mkchrootpkg_args+=(-n) ;;
-	s) sign=true ;;
-	q) pretend=true ;;
-	h|?) usage 0 ;;
-        *) echo "invalid argument '${arg}'"; usage 1 ;;
-    esac
+	case "${arg}" in
+		p) buildset_pkg="$OPTARG" ;;
+		a) arch="$OPTARG" ;;
+		b) branch="$OPTARG" ;;
+		r) chroots_pkg="$OPTARG" ;;
+		c) clean_first=true; mkchroot_args+=(-L) ;;
+		w) wipe_clean=true ;;
+		n) namcap=true; mkchrootpkg_args+=(-n) ;;
+		s) sign=true ;;
+		q) pretend=true ;;
+		h|?) usage 0 ;;
+		*) echo "invalid argument '${arg}'"; usage 1 ;;
+	esac
 done
 
 if [[ "${arch}" == 'multilib' ]]; then
-    pacman_conf_arch='multilib'
-    base_packages+=('multilib-devel')
-    work_dir=${chroots_pkg}/${branch}/${arch}
-    cache_dir_pkg=${cache_dir}/${branch}/${arch}
-    arch='x86_64'
-    is_multilib=true
+	pacman_conf_arch='multilib'
+	base_packages+=('multilib-devel')
+	work_dir=${chroots_pkg}/${branch}/${arch}
+	cache_dir_pkg=${cache_dir}/${branch}/${arch}
+	arch='x86_64'
+	is_multilib=true
 else
-    work_dir=${chroots_pkg}/${branch}/${arch}
-    cache_dir_pkg=${cache_dir}/${branch}/${arch}
-    is_multilib=false
+	work_dir=${chroots_pkg}/${branch}/${arch}
+	cache_dir_pkg=${cache_dir}/${branch}/${arch}
+	is_multilib=false
 fi
 
 pacman_conf="${PKGDATADIR}/pacman-${pacman_conf_arch}.conf"
diff --git a/bin/buildtree.in b/bin/buildtree.in
--- a/bin/buildtree.in
+++ b/bin/buildtree.in
@@ -18,66 +18,66 @@ SYSCONFDIR='@sysconfdir@'
 [[ -r ${LIBDIR}/util.sh ]] && source ${LIBDIR}/util.sh
 
 display_settings(){
-    msg "manjaro-tools"
-    msg2 "version: ${version}"
+	msg "manjaro-tools"
+	msg2 "version: ${version}"
 
-    if [[ -f ${USER_CONFIG}/manjaro-tools.conf ]]; then
+	if [[ -f ${USER_CONFIG}/manjaro-tools.conf ]]; then
 	msg2 "user_config: ${USER_CONFIG}/manjaro-tools.conf"
-    else
+	else
 	msg2 "manjaro_tools_conf: ${manjaro_tools_conf}"
-    fi
+	fi
 
-    msg "ARGS:"
-    msg2 "sync: ${sync}"
-    msg2 "abs: ${abs}"
-    msg2 "clean: ${clean}"
+	msg "ARGS:"
+	msg2 "sync: ${sync}"
+	msg2 "abs: ${abs}"
+	msg2 "clean: ${clean}"
 
-    msg "PATHS:"
-    msg2 "tree_dir: ${tree_dir}"
-    msg2 "repo_tree: ${repo_tree[*]}"
-    msg2 "host_tree: ${host_tree}"
-    msg2 "host_tree_abs: ${host_tree_abs}"
+	msg "PATHS:"
+	msg2 "tree_dir: ${tree_dir}"
+	msg2 "repo_tree: ${repo_tree[*]}"
+	msg2 "host_tree: ${host_tree}"
+	msg2 "host_tree_abs: ${host_tree_abs}"
 }
 
 prepare_dir(){
-    [[ ! -d $1 ]] && mkdir -p $1
+	[[ ! -d $1 ]] && mkdir -p $1
 }
 
 sync_tree(){
-    cd ${tree_dir}
-    for repo in ${repo_tree[@]};do
-	if [[ -d packages-$repo ]];then
-	    cd packages-$repo
-	    msg "Syncing $repo ..."
-	    git pull origin master
-	    cd ..
-	else
-	    msg "Cloning $repo ..."
-	    git clone --depth 1 ${host_tree}/packages-$repo.git
-	fi
-    done
-    cd ..
+	cd ${tree_dir}
+	for repo in ${repo_tree[@]};do
+		if [[ -d packages-$repo ]];then
+			cd packages-$repo
+			msg "Syncing $repo ..."
+			git pull origin master
+			cd ..
+		else
+			msg "Cloning $repo ..."
+			git clone --depth 1 ${host_tree}/packages-$repo.git
+		fi
+	done
+	cd ..
 }
 
 sync_tree_abs(){
-    cd ${tree_dir}/abs
-    if [[ -d packages ]];then
-	cd packages
-	msg "Syncing abs ..."
-	git pull origin master
+	cd ${tree_dir}/abs
+	if [[ -d packages ]];then
+		cd packages
+		msg "Syncing abs ..."
+		git pull origin master
+		cd ..
+	else
+		msg "Cloning abs ..."
+		git clone --depth 1 ${host_tree_abs}.git
+	fi
 	cd ..
-    else
-	msg "Cloning abs ..."
-	git clone --depth 1 ${host_tree_abs}.git
-    fi
-    cd ..
 }
 
 clean_tree_dir(){
-    if [[ -d ${tree_dir} ]]; then
-	msg "Cleaning ${tree_dir} ..."
-	rm -r ${tree_dir}/*
-    fi
+	if [[ -d ${tree_dir} ]]; then
+		msg "Cleaning ${tree_dir} ..."
+		rm -r ${tree_dir}/*
+	fi
 }
 
 load_user_info
@@ -91,15 +91,15 @@ abs=false
 clean=false
 
 usage() {
-    echo "Usage: ${0##*/} [options]"
-    echo "    -s            Sync manjaro tree"
-    echo "    -a            Sync arch abs"
-    echo '    -c            Clean package tree'
-    echo '    -q            Query settings'
-    echo '    -h            This help'
-    echo ''
-    echo ''
-    exit $1
+	echo "Usage: ${0##*/} [options]"
+	echo "    -s            Sync manjaro tree"
+	echo "    -a            Sync arch abs"
+	echo '    -c            Clean package tree'
+	echo '    -q            Query settings'
+	echo '    -h            This help'
+	echo ''
+	echo ''
+	exit $1
 }
 
 orig_argv=("$@")
@@ -107,14 +107,14 @@ orig_argv=("$@")
 opts='sacqh'
 
 while getopts "${opts}" arg; do
-    case "${arg}" in
-	s) sync=true ;;
-	a) abs=true ;;
-	c) clean=true ;;
-	q) pretend=true ;;
-	h|?) usage 0 ;;
-        *) echo "invalid argument '${arg}'"; usage 1 ;;
-    esac
+	case "${arg}" in
+		s) sync=true ;;
+		a) abs=true ;;
+		c) clean=true ;;
+		q) pretend=true ;;
+		h|?) usage 0 ;;
+		*) echo "invalid argument '${arg}'"; usage 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
diff --git a/bin/mkiso.in b/bin/mkiso.in
--- a/bin/mkiso.in
+++ b/bin/mkiso.in
@@ -30,64 +30,63 @@ APPNAME=$(basename "${0}")
 MIRRORS=''
 
 # usage: usage <exitvalue>
-usage ()
-{
-    echo "usage ${APPNAME} [options] command <command options>"
-    echo " general options:"
-    echo "    -f                Force overwrite of working files/squashfs image/bootable image"
-    echo "    -p PACKAGE(S)     Additional package(s) to install, can be used multiple times"
-    echo "    -C <file>         Config file for pacman. Default $PACCONFIG"
-    echo "    -L <label>        Set a label for the disk"
-    echo "    -P <publisher>    Set a publisher for the disk"
-    echo "    -A <application>  Set an application name for the disk"
-    echo "    -a <arch>         Set an architecture for the disk (example: i686)"
-    echo "    -c <compressor>   Set SquashFS compression type: gzip, xz or lzo. Default $COMPRESSION"
-    echo "                      NOTES:"
-    echo "                            xz: needs Linux >= 2.6.35 - you can add '-x' for better compression"
-    echo "                            lzo:  needs Linux >= 2.6.36"
-    echo "    -D <install_dir>  Set an install_dir. All files will by located here on ISO (except for isolinux)"
-    echo "                      Default $INSTALL_DIR"
-    echo "                      NOTE: Max 8 characters, use only [a-z0-9]"
-    echo "    -i <image_folder> Set an image_folder for installing selected packages to."
-    echo "                      Default $IMAGE_FOLDER"
-    echo "    -d                Create default user directory /home/manjaro"
-    echo "    -v                Enable verbose output"
-    echo "    -M                Pass pacman-mirrors.conf"
-    echo "    -h                This message"
-    echo " commands:"
-    echo "   create <dir>"
-    echo "      create a base directory layout to work with"
-    echo "      includes all specified packages"
-    echo "   iso <dir> <image name>"
-    echo "      build an iso image from the working dir"
-    exit $1
+usage (){
+	echo "usage ${APPNAME} [options] command <command options>"
+	echo " general options:"
+	echo "    -f                Force overwrite of working files/squashfs image/bootable image"
+	echo "    -p PACKAGE(S)     Additional package(s) to install, can be used multiple times"
+	echo "    -C <file>         Config file for pacman. Default $PACCONFIG"
+	echo "    -L <label>        Set a label for the disk"
+	echo "    -P <publisher>    Set a publisher for the disk"
+	echo "    -A <application>  Set an application name for the disk"
+	echo "    -a <arch>         Set an architecture for the disk (example: i686)"
+	echo "    -c <compressor>   Set SquashFS compression type: gzip, xz or lzo. Default $COMPRESSION"
+	echo "                      NOTES:"
+	echo "                            xz: needs Linux >= 2.6.35 - you can add '-x' for better compression"
+	echo "                            lzo:  needs Linux >= 2.6.36"
+	echo "    -D <install_dir>  Set an install_dir. All files will by located here on ISO (except for isolinux)"
+	echo "                      Default $INSTALL_DIR"
+	echo "                      NOTE: Max 8 characters, use only [a-z0-9]"
+	echo "    -i <image_folder> Set an image_folder for installing selected packages to."
+	echo "                      Default $IMAGE_FOLDER"
+	echo "    -d                Create default user directory /home/manjaro"
+	echo "    -v                Enable verbose output"
+	echo "    -M                Pass pacman-mirrors.conf"
+	echo "    -h                This message"
+	echo " commands:"
+	echo "   create <dir>"
+	echo "      create a base directory layout to work with"
+	echo "      includes all specified packages"
+	echo "   iso <dir> <image name>"
+	echo "      build an iso image from the working dir"
+	exit $1
 }
 
 orig_argv=("$@")
 
 while getopts 'p:C:L:P:A:a:c:M:D:i:dfvhx' arg; do
-    case "${arg}" in
-        p) PKGLIST="${PKGLIST} ${OPTARG}" ;;
-        C) PACCONFIG="${OPTARG}" ;;
-        L) LABEL="${OPTARG}" ;;
-        P) PUBLISHER="${OPTARG}" ;;
-        A) APPLICATION="${OPTARG}" ;;
-        a) ARCH="${OPTARG}" ;;
-        c) COMPRESSION="${OPTARG}" ;;
-        D) INSTALL_DIR="${OPTARG}" ;;
-        i) IMAGE_FOLDER="${OPTARG}" ;;
-        d) CREATE_DEFAULT=true ;;
-        f) FORCE=true ;;
-        x) HIGHCOMP=" -b 256K -Xbcj x86" ;;
-        v) QUIET=false ;;
-        M) MIRRORS="${OPTARG}" ;;
-        h|?) usage 0 ;;
-        *) echo "invalid argument '${arg}'"; usage 1 ;;
-    esac
+	case "${arg}" in
+		p) PKGLIST="${PKGLIST} ${OPTARG}" ;;
+		C) PACCONFIG="${OPTARG}" ;;
+		L) LABEL="${OPTARG}" ;;
+		P) PUBLISHER="${OPTARG}" ;;
+		A) APPLICATION="${OPTARG}" ;;
+		a) ARCH="${OPTARG}" ;;
+		c) COMPRESSION="${OPTARG}" ;;
+		D) INSTALL_DIR="${OPTARG}" ;;
+		i) IMAGE_FOLDER="${OPTARG}" ;;
+		d) CREATE_DEFAULT=true ;;
+		f) FORCE=true ;;
+		x) HIGHCOMP=" -b 256K -Xbcj x86" ;;
+		v) QUIET=false ;;
+		M) MIRRORS="${OPTARG}" ;;
+		h|?) usage 0 ;;
+		*) echo "invalid argument '${arg}'"; usage 1 ;;
+	esac
 done
 
 if [ "${COMPRESSION}" != "xz" ]; then
-    HIGHCOMP=""
+	HIGHCOMP=""
 fi
 
 #trim spaces
@@ -98,7 +97,7 @@ shift $(($OPTIND - 1))
 check_root "$0" "${orig_argv[@]}"
 
 if [ ! -f "$PACCONFIG" ]; then
-    error "pacman config file '$PACCONFIG' does not exist"
+	error "pacman config file '$PACCONFIG' does not exist"
 fi
 
 command_name="${1}"
@@ -106,9 +105,9 @@ work_dir=""
 imgname=""
 
 case "${command_name}" in
-    create) work_dir="${2}"; imgname="none" ;;
-    iso) work_dir="${2}"; imgname="${3}" ;;
-    *) error "Invalid command name ${command_name}" && usage 1 ;;
+	create) work_dir="${2}"; imgname="none" ;;
+	iso) work_dir="${2}"; imgname="${3}" ;;
+	*) error "Invalid command name ${command_name}" && usage 1 ;;
 esac
 
 [[ -z "${ARCH}" ]] && error "You need to specify an architecture:\ni686\nx86_64" && usage 1
@@ -121,188 +120,188 @@ msg2 "image name: ${imgname}"
 msg2 "pacman_mirrors: ${MIRRORS}"
 
 clean_up(){
-    msg2 "Cleaning up what we can"
-    if [ -d "${work_dir}/${IMAGE_FOLDER}/boot/" ]; then
+	msg2 "Cleaning up what we can"
+	if [ -d "${work_dir}/${IMAGE_FOLDER}/boot/" ]; then
 	# remove the initcpio images that were generated for the host system
 	find "${work_dir}/${IMAGE_FOLDER}/boot" -name 'initramfs*.img' -delete &>/dev/null
-    fi
-
-    if ${CREATE_DEFAULT}; then
-	if [ -d "${work_dir}/${IMAGE_FOLDER}/home/" ]; then
-	    msg2 "Creating default home directory"
-	    install -d -o1000 -g100 -m0755 "${work_dir}/${IMAGE_FOLDER}/home/${username}"
 	fi
-    fi
 
-    [[ -f "${work_dir}/${IMAGE_FOLDER}/etc/locale.gen.bak" ]] \
+	if ${CREATE_DEFAULT}; then
+	if [ -d "${work_dir}/${IMAGE_FOLDER}/home/" ]; then
+		msg2 "Creating default home directory"
+		install -d -o1000 -g100 -m0755 "${work_dir}/${IMAGE_FOLDER}/home/${username}"
+	fi
+	fi
+
+	[[ -f "${work_dir}/${IMAGE_FOLDER}/etc/locale.gen.bak" ]] \
 	&& mv "${work_dir}/${IMAGE_FOLDER}/etc/locale.gen.bak" "${work_dir}/${IMAGE_FOLDER}/etc/locale.gen"
-    [[ -f "${work_dir}/${IMAGE_FOLDER}/etc/locale.conf.bak" ]] \
+	[[ -f "${work_dir}/${IMAGE_FOLDER}/etc/locale.conf.bak" ]] \
 	&& mv "${work_dir}/${IMAGE_FOLDER}/etc/locale.conf.bak" "${work_dir}/${IMAGE_FOLDER}/etc/locale.conf"
 
-    # Delete pacman database sync cache files (*.tar.gz)
-    find "${work_dir}/${IMAGE_FOLDER}/var/lib/pacman" -maxdepth 1 -type f -delete &>/dev/null
-    # Delete pacman database sync cache
-    find "${work_dir}/${IMAGE_FOLDER}/var/lib/pacman/sync" -delete &>/dev/null
-    # Delete pacman package cache
-    find "${work_dir}/${IMAGE_FOLDER}/var/cache/pacman/pkg" -type f -delete &>/dev/null
-    # Delete all log files, keeps empty dirs.
-    find "${work_dir}/${IMAGE_FOLDER}/var/log" -type f -delete &>/dev/null
-    # Delete all temporary files and dirs
-    find "${work_dir}/${IMAGE_FOLDER}/var/tmp" -mindepth 1 -delete &>/dev/null
-    # Delete all temporary files and dirs
-    find "${work_dir}/${IMAGE_FOLDER}/tmp" -mindepth 1 -delete &>/dev/null
+	# Delete pacman database sync cache files (*.tar.gz)
+	find "${work_dir}/${IMAGE_FOLDER}/var/lib/pacman" -maxdepth 1 -type f -delete &>/dev/null
+	# Delete pacman database sync cache
+	find "${work_dir}/${IMAGE_FOLDER}/var/lib/pacman/sync" -delete &>/dev/null
+	# Delete pacman package cache
+	find "${work_dir}/${IMAGE_FOLDER}/var/cache/pacman/pkg" -type f -delete &>/dev/null
+	# Delete all log files, keeps empty dirs.
+	find "${work_dir}/${IMAGE_FOLDER}/var/log" -type f -delete &>/dev/null
+	# Delete all temporary files and dirs
+	find "${work_dir}/${IMAGE_FOLDER}/var/tmp" -mindepth 1 -delete &>/dev/null
+	# Delete all temporary files and dirs
+	find "${work_dir}/${IMAGE_FOLDER}/tmp" -mindepth 1 -delete &>/dev/null
 }
 
 _mkchroot(){
 	#set locale.gen
 	if [ "${IMAGE_FOLDER}" == "root-image" ]; then
-	    LOCALE="-L"
+		LOCALE="-L"
 	fi
 
 	#local ret
 	if "${QUIET}"; then
-	    setarch "${ARCH}" \
+		setarch "${ARCH}" \
 		mkchroot -C ${PACCONFIG} \
 		-S ${MIRRORS} \
 		${LOCALE} \
 		"${work_dir}/${IMAGE_FOLDER}" $@ &> /dev/null || die "Failed to retrieve one or more packages!"
 	else
-	    setarch "${ARCH}" \
+		setarch "${ARCH}" \
 		mkchroot -C ${PACCONFIG} \
 		-S ${MIRRORS} \
 		${LOCALE} \
 		"${work_dir}/${IMAGE_FOLDER}" $@ || die "Failed to retrieve one or more packages!"
 	fi
-	
+
 	# Cleanup
 	find "${work_dir}" -name *.pacnew -name *.pacsave -name *.pacorig -delete
 }
 
 command_create () {
-    mkdir -p "${work_dir}/iso/${INSTALL_DIR}/${ARCH}"
+	mkdir -p "${work_dir}/iso/${INSTALL_DIR}/${ARCH}"
 
-    [[ -n "${PKGLIST}" ]] && _mkchroot "${PKGLIST}" && clean_up
+	[[ -n "${PKGLIST}" ]] && _mkchroot "${PKGLIST}" && clean_up
 }
 
 # _mksquash dirname
 _mksquash () {
-    if [ ! -d "$1" ]; then
-        error "$1 is not a directory"
-        return 1
-    fi
+	if [ ! -d "$1" ]; then
+		error "$1 is not a directory"
+		return 1
+	fi
 
-    sqimg="${work_dir}/iso/${INSTALL_DIR}/${ARCH}/$(basename ${1}).sqfs"
-    msg "Generating SquashFS image for '${1}'"
-    if [ -e "${sqimg}" ]; then
-        dirhaschanged=$(find ${1} -newer ${sqimg})
-        msg2 "Possible changes for ${1}..." >> /tmp/mkiso.debug
-        msg2 "${dirhaschanged}" >> /tmp/mkiso.debug
-        if [ ! -z "${dirhaschanged}" ]; then
-            msg2 "SquashFS image '${sqimg}' is not up to date, rebuilding..."
-            rm "${sqimg}"
-        else
-            msg2 "SquashFS image '${sqimg}' is up to date, skipping."
-            return
-        fi
-    fi
+	sqimg="${work_dir}/iso/${INSTALL_DIR}/${ARCH}/$(basename ${1}).sqfs"
+	msg "Generating SquashFS image for '${1}'"
+	if [ -e "${sqimg}" ]; then
+		dirhaschanged=$(find ${1} -newer ${sqimg})
+		msg2 "Possible changes for ${1}..." >> /tmp/mkiso.debug
+		msg2 "${dirhaschanged}" >> /tmp/mkiso.debug
+		if [ ! -z "${dirhaschanged}" ]; then
+			msg2 "SquashFS image '${sqimg}' is not up to date, rebuilding..."
+			rm "${sqimg}"
+		else
+			msg2 "SquashFS image '${sqimg}' is up to date, skipping."
+			return
+		fi
+	fi
 
-    msg2 "Creating SquashFS image. This may take some time..."
-    start=$(date +%s)
-    if "${QUIET}"; then
-        mksquashfs "${1}" "${sqimg}" -noappend -comp "${COMPRESSION}" ${HIGHCOMP} >/dev/null
-    else
-        mksquashfs "${1}" "${sqimg}" -noappend -comp "${COMPRESSION}" ${HIGHCOMP}
-    fi
-    minutes=$(echo $start $(date +%s) | awk '{ printf "%0.2f",($2-$1)/60 }')
-    msg "Image creation done in $minutes minutes."
+	msg2 "Creating SquashFS image. This may take some time..."
+	start=$(date +%s)
+	if "${QUIET}"; then
+		mksquashfs "${1}" "${sqimg}" -noappend -comp "${COMPRESSION}" ${HIGHCOMP} >/dev/null
+	else
+		mksquashfs "${1}" "${sqimg}" -noappend -comp "${COMPRESSION}" ${HIGHCOMP}
+	fi
+	minutes=$(echo $start $(date +%s) | awk '{ printf "%0.2f",($2-$1)/60 }')
+	msg "Image creation done in $minutes minutes."
 }
 
 _imgcommon () {
-    for d in $(find "${work_dir}" -maxdepth 1 -type d -name '[^.]*'); do
-        if [ "$d" != "${work_dir}/iso" -a \
-             "$(basename "$d")" != "iso" -a \
-             "$(basename "$d")" != "efiboot" -a \
-             "$d" != "${work_dir}" ]; then
-            _mksquash "$d"
-        fi
-    done
+	for d in $(find "${work_dir}" -maxdepth 1 -type d -name '[^.]*'); do
+		if [ "$d" != "${work_dir}/iso" -a \
+			"$(basename "$d")" != "iso" -a \
+			"$(basename "$d")" != "efiboot" -a \
+			"$d" != "${work_dir}" ]; then
+			_mksquash "$d"
+		fi
+	done
 
-    msg "Making bootable image"
+	msg "Making bootable image"
 
-    # Sanity checks
-    if [ ! -d "${work_dir}/iso" ]; then
-        die "${work_dir}/iso doesn't exist. What did you do?!"
-    fi
+	# Sanity checks
+	if [ ! -d "${work_dir}/iso" ]; then
+		die "${work_dir}/iso doesn't exist. What did you do?!"
+	fi
 
-    if [ ! -f "${work_dir}/iso/${INSTALL_DIR}/isomounts" ]; then
-        error "The isomounts file doesn't exist. This image won't do anything"
-        die "Protecting you from yourself and erroring out here..."
-    fi
+	if [ ! -f "${work_dir}/iso/${INSTALL_DIR}/isomounts" ]; then
+		error "The isomounts file doesn't exist. This image won't do anything"
+		die "Protecting you from yourself and erroring out here..."
+	fi
 
-    if [ -e "${imgname}" ]; then
-        if "${FORCE}"; then
-            msg2 "Removing existing bootable image..."
-            rm -rf "${imgname}"
-        else
-            error "Image ${imgname} already exists."
-            abort
-        fi
-    fi
+	if [ -e "${imgname}" ]; then
+		if "${FORCE}"; then
+			msg2 "Removing existing bootable image..."
+			rm -rf "${imgname}"
+		else
+			error "Image ${imgname} already exists."
+			abort
+		fi
+	fi
 
-    if ! sed "s|%MANJAROISO_LABEL%|${LABEL}|g;
-              s|%INSTALL_DIR%|${INSTALL_DIR}|g;
-              s|%ARCH%|${ARCH}|g" -i ${work_dir}/iso/isolinux/*.cfg; then
+	if ! sed "s|%MANJAROISO_LABEL%|${LABEL}|g;
+			s|%INSTALL_DIR%|${INSTALL_DIR}|g;
+			s|%ARCH%|${ARCH}|g" -i ${work_dir}/iso/isolinux/*.cfg; then
 	die "${work_dir}/iso/isolinux/isolinux.cfg, doesn't exist."
-    fi
+	fi
 
-    if [ ! -f "${work_dir}/iso/isolinux/isolinux.bin" ]; then
+	if [ ! -f "${work_dir}/iso/isolinux/isolinux.bin" ]; then
 	die "${work_dir}/iso/isolinux/isolinux.bin, doesn't exist."
-    fi
-    if [ ! -f "${work_dir}/iso/isolinux/isohdpfx.bin" ]; then
-	die "${work_dir}/iso/isolinux/isohdpfx.bin, doesn't exist." 
-    fi
+	fi
+	if [ ! -f "${work_dir}/iso/isolinux/isohdpfx.bin" ]; then
+	die "${work_dir}/iso/isolinux/isohdpfx.bin, doesn't exist."
+	fi
 }
 
 command_iso () {
-    _imgcommon
+	_imgcommon
 
-    _iso_efi_boot_args=""
+	_iso_efi_boot_args=""
 
-    # If exists, add an EFI "El Torito" boot image (FAT filesystem) to ISO-9660 image.
-    if [ -f "${work_dir}/iso/EFI/miso/manjaro.img" ]; then
-        _iso_efi_boot_args="-eltorito-alt-boot -e EFI/miso/manjaro.img \
-                            -isohybrid-gpt-basdat -no-emul-boot"
-    fi
+	# If exists, add an EFI "El Torito" boot image (FAT filesystem) to ISO-9660 image.
+	if [ -f "${work_dir}/iso/EFI/miso/manjaro.img" ]; then
+		_iso_efi_boot_args="-eltorito-alt-boot -e EFI/miso/manjaro.img \
+							-isohybrid-gpt-basdat -no-emul-boot"
+	fi
 
-    msg "Creating ISO image..."
-    ## Generate the BIOS+ISOHYBRID CD image using xorriso (extra/libisoburn package) in mkisofs emulation mode
-    _qflag=""
-    if ${QUIET}; then
-        _qflag="-quiet"
-    fi
-    xorriso -as mkisofs ${_qflag} \
-            -iso-level 3 -rock -joliet \
-            -max-iso9660-filenames -omit-period \
-            -omit-version-number \
-            -relaxed-filenames -allow-lowercase \
-            -volid "${LABEL}" \
-            -appid "${APPLICATION}" \
-            -publisher "${PUBLISHER}" \
-            -preparer "prepared by mkmiso" \
-            -eltorito-boot isolinux/isolinux.bin \
-            -eltorito-catalog isolinux/boot.cat \
-            -no-emul-boot -boot-load-size 4 -boot-info-table \
-            -isohybrid-mbr "${work_dir}/iso/isolinux/isohdpfx.bin" \
-            ${_iso_efi_boot_args} \
-            -output "${imgname}" \
-            "${work_dir}/iso/"
+	msg "Creating ISO image..."
+	## Generate the BIOS+ISOHYBRID CD image using xorriso (extra/libisoburn package) in mkisofs emulation mode
+	_qflag=""
+	if ${QUIET}; then
+		_qflag="-quiet"
+	fi
+	xorriso -as mkisofs ${_qflag} \
+			-iso-level 3 -rock -joliet \
+			-max-iso9660-filenames -omit-period \
+			-omit-version-number \
+			-relaxed-filenames -allow-lowercase \
+			-volid "${LABEL}" \
+			-appid "${APPLICATION}" \
+			-publisher "${PUBLISHER}" \
+			-preparer "prepared by mkmiso" \
+			-eltorito-boot isolinux/isolinux.bin \
+			-eltorito-catalog isolinux/boot.cat \
+			-no-emul-boot -boot-load-size 4 -boot-info-table \
+			-isohybrid-mbr "${work_dir}/iso/isolinux/isohdpfx.bin" \
+			${_iso_efi_boot_args} \
+			-output "${imgname}" \
+			"${work_dir}/iso/"
 }
 
 # Go through the main commands in order. If 'all' was specified, then we want
 # to do everything. Start with 'install'.
 if [ "${command_name}" = "create"  ]; then
-    command_create
+	command_create
 fi
 if [ "${command_name}" = "iso" ]; then
-    command_iso
+	command_iso
 fi
diff --git a/bin/mkset.in b/bin/mkset.in
--- a/bin/mkset.in
+++ b/bin/mkset.in
@@ -17,35 +17,35 @@ SYSCONFDIR='@sysconfdir@'
 [[ -r @libdir@/util.sh ]] && source @libdir@/util.sh
 
 create_set(){
-    msg "[$1/${name}.set]"
-    if [[ -f $1/${name}.set ]];then
-	msg3 "Backing up $1/${name}.set.orig"
-	mv "$1/${name}.set" "$1/${name}.set.orig"
-    fi
-    local list=$(find * -maxdepth 0 -type d | sort)
-    for item in ${list[@]};do
-	if [[ -f $item/$2 ]];then
-	    cd $item
-		msg2 "Adding ${item##*/}"
-		echo ${item##*/} >> $1/${name}.set || break
-	    cd ..
+	msg "[$1/${name}.set]"
+	if [[ -f $1/${name}.set ]];then
+		msg3 "Backing up $1/${name}.set.orig"
+		mv "$1/${name}.set" "$1/${name}.set.orig"
 	fi
-    done
+	local list=$(find * -maxdepth 0 -type d | sort)
+	for item in ${list[@]};do
+		if [[ -f $item/$2 ]];then
+			cd $item
+				msg2 "Adding ${item##*/}"
+				echo ${item##*/} >> $1/${name}.set || break
+			cd ..
+		fi
+	done
 }
 
 remove_set(){
-    if [[ -f $1/${name}.set ]]; then
-	msg "Removing [$1/${name}.set] ..."
-	rm $1/${name}.set
-    fi
+	if [[ -f $1/${name}.set ]]; then
+		msg "Removing [$1/${name}.set] ..."
+		rm $1/${name}.set
+	fi
 }
 
 show_set(){
-    local list=$(cat $1/${name}.set)
-    msg "Content of [$1/${name}.set] ..."
-    for item in ${list[@]}; do
-	msg2 "$item"
-    done
+	local list=$(cat $1/${name}.set)
+	msg "Content of [$1/${name}.set] ..."
+	for item in ${list[@]}; do
+		msg2 "$item"
+	done
 }
 
 load_user_info
@@ -62,16 +62,16 @@ iso_mode=false
 name='default'
 
 usage() {
-    echo "Usage: ${0##*/} [options]"
-    echo "    -c <name>   Create set"
-    echo "    -r <name>   Remove set"
-    echo "    -s <name>   Show set"
-    echo "    -i          Iso mode"
-    echo "    -q          Query sets"
-    echo '    -h          This help'
-    echo ''
-    echo ''
-    exit $1
+	echo "Usage: ${0##*/} [options]"
+	echo "    -c <name>   Create set"
+	echo "    -r <name>   Remove set"
+	echo "    -s <name>   Show set"
+	echo "    -i          Iso mode"
+	echo "    -q          Query sets"
+	echo '    -h          This help'
+	echo ''
+	echo ''
+	exit $1
 }
 
 orig_argv=("$@")
@@ -79,15 +79,15 @@ orig_argv=("$@")
 opts='c:r:s:qih'
 
 while getopts "${opts}" arg; do
-    case "${arg}" in
-	c) name="$OPTARG"; create=true ;;
-	r) name="$OPTARG"; remove=true ;;
-	s) name="$OPTARG"; show=true;;
-	i) iso_mode=true ;;
-	q) query=true ;;
-	h|?) usage 0 ;;
-        *) echo "invalid argument '${arg}'"; usage 1 ;;
-    esac
+	case "${arg}" in
+		c) name="$OPTARG"; create=true ;;
+		r) name="$OPTARG"; remove=true ;;
+		s) name="$OPTARG"; show=true;;
+		i) iso_mode=true ;;
+		q) query=true ;;
+		h|?) usage 0 ;;
+		*) echo "invalid argument '${arg}'"; usage 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
@@ -95,28 +95,27 @@ shift $(($OPTIND - 1))
 check_root "$0" "${orig_argv[@]}"
 
 if ${create};then
-    if ${iso_mode}; then
-	create_set "${sets_dir_iso}" "initsys"
-    else
-	create_set "${sets_dir_pkg}" "PKGBUILD"
-    fi
+	if ${iso_mode}; then
+		create_set "${sets_dir_iso}" "initsys"
+	else
+		create_set "${sets_dir_pkg}" "PKGBUILD"
+	fi
 elif ${remove};then
-    if ${iso_mode}; then
-        remove_set "${sets_dir_iso}"
-    else
-        remove_set "${sets_dir_pkg}"
-    fi
+	if ${iso_mode}; then
+		remove_set "${sets_dir_iso}"
+	else
+		remove_set "${sets_dir_pkg}"
+	fi
 elif ${show};then
-    if ${iso_mode}; then
-        show_set "${sets_dir_iso}"
-    else
-        show_set "${sets_dir_pkg}"
-    fi
+	if ${iso_mode}; then
+		show_set "${sets_dir_iso}"
+	else
+		show_set "${sets_dir_pkg}"
+	fi
 else
-    if ${iso_mode}; then
-        msg "Available sets: $(load_sets ${sets_dir_iso})"
-    else
-        msg "Available sets: $(load_sets ${sets_dir_pkg})"
-    fi
-
+	if ${iso_mode}; then
+		msg "Available sets: $(load_sets ${sets_dir_iso})"
+	else
+		msg "Available sets: $(load_sets ${sets_dir_pkg})"
+	fi
 fi
