[buildpkg] rename -> cache_dir_pkg

diff --git a/bin/buildpkg.in b/bin/buildpkg.in
--- a/bin/buildpkg.in
+++ b/bin/buildpkg.in
@@ -52,7 +52,7 @@ display_settings(){
     msg "PATHS:"
     msg2 "work_dir: ${work_dir}"
     msg2 "sets_dir_pkg: ${sets_dir_pkg}"
-    msg2 "pkg_dir: ${pkg_dir}"
+    msg2 "cache_dir_pkg: ${cache_dir_pkg}"
     #     msg2 "pacman_conf: ${pacman_conf}"
     #     msg2 "makepkg_conf: ${makepkg_conf}"
     #     msg2 "mirrors_conf: ${mirrors_conf}"
@@ -125,7 +125,7 @@ usage() {
     echo '    -h                 This help'
     echo ''
     echo ''
-    exit 1
+    exit $1
 }
 
 orig_argv=("$@")
@@ -143,7 +143,8 @@ while getopts "${opts}" arg; do
 	n) namcap=true; mkchrootpkg_args+=(-n) ;;
 	s) sign=true ;;
 	q) pretend=true ;;
-	h) usage ;;
+	h|?) usage 0 ;;
+        *) echo "invalid argument '${arg}'"; usage 1 ;;
     esac
 done
 
@@ -155,7 +156,7 @@ fi
 
 work_dir=${chroots_pkg}/${branch}/${arch}
 
-pkg_dir="${cache_dir}/${branch}/${arch}"
+cache_dir_pkg="${cache_dir}/${branch}/${arch}"
 sets_dir_pkg="${sets_dir}/pkg"
 
 pacman_conf="${PKGDATADIR}/pacman-${pacman_conf_arch}.conf"
