default format of 4 spaces

diff --git a/bin/buildpkg.in b/bin/buildpkg.in
--- a/bin/buildpkg.in
+++ b/bin/buildpkg.in
@@ -23,52 +23,52 @@ import ${LIBDIR}/util.sh
 import ${LIBDIR}/util-pkg.sh
 
 show_pkg(){
-	check_build "$1"
-	cd $1
-		source PKGBUILD
-		for n in ${pkgname[@]}; do
-			msg2 "%s" "$n"
-		done
-	cd ..
+    check_build "$1"
+    cd $1
+        source PKGBUILD
+        for n in ${pkgname[@]}; do
+            msg2 "%s" "$n"
+        done
+    cd ..
 }
 
 display_settings(){
-	show_version
-	show_config
+    show_version
+    show_config
 
-	msg "PROFILE:"
-	msg2 "list_dir_pkg: %s" "${list_dir_pkg}"
-	msg2 "build_lists: %s" "$(show_build_lists ${list_dir_pkg})"
-	msg2 "build_list_pkg: %s" "${build_list_pkg}"
-	msg2 "is_build_list: %s" "${is_build_list}"
-	msg2 "build_mirror: %s" "${build_mirror}/${target_branch}"
+    msg "PROFILE:"
+    msg2 "list_dir_pkg: %s" "${list_dir_pkg}"
+    msg2 "build_lists: %s" "$(show_build_lists ${list_dir_pkg})"
+    msg2 "build_list_pkg: %s" "${build_list_pkg}"
+    msg2 "is_build_list: %s" "${is_build_list}"
+    msg2 "build_mirror: %s" "${build_mirror}/${target_branch}"
 # 	msg2 "make_conf_dir: %s" "${make_conf_dir}"
 # 	msg2 "build_profiles: %s" "$(show_build_profiles ${make_conf_dir})"
 
-	msg "OPTIONS:"
-	msg2 "arch: %s" "${target_arch}"
-	msg2 "branch: %s" "${target_branch}"
-	msg2 "chroots_pkg: %s" "${chroots_pkg}"
+    msg "OPTIONS:"
+    msg2 "arch: %s" "${target_arch}"
+    msg2 "branch: %s" "${target_branch}"
+    msg2 "chroots_pkg: %s" "${chroots_pkg}"
 
 
-	msg "ARGS:"
-	msg2 "clean_first: %s" "${clean_first}"
-	msg2 "wipe_clean: %s" "${wipe_clean}"
-	msg2 "namcap: %s" "${namcap}"
-	msg2 "sign: %s" "${sign}"
-	msg2 "udev_root: %s" "${udev_root}"
+    msg "ARGS:"
+    msg2 "clean_first: %s" "${clean_first}"
+    msg2 "wipe_clean: %s" "${wipe_clean}"
+    msg2 "namcap: %s" "${namcap}"
+    msg2 "sign: %s" "${sign}"
+    msg2 "udev_root: %s" "${udev_root}"
 
-	msg "PATHS:"
-	msg2 "work_dir: %s" "${work_dir}"
-	msg2 "pkg_dir: %s" "${pkg_dir}"
+    msg "PATHS:"
+    msg2 "work_dir: %s" "${work_dir}"
+    msg2 "pkg_dir: %s" "${pkg_dir}"
 
-	if ${clean_first};then
-		msg "PKG:"
-		msg2 "base_packages: %s" "${base_packages[*]}"
-	fi
+    if ${clean_first};then
+        msg "PKG:"
+        msg2 "base_packages: %s" "${base_packages[*]}"
+    fi
 
-	msg "BUILD QUEUE:"
-	run show_pkg "${build_list_pkg}"
+    msg "BUILD QUEUE:"
+    run show_pkg "${build_list_pkg}"
 }
 
 load_user_info
@@ -88,23 +88,23 @@ udev_root=false
 is_multilib=false
 
 usage() {
-	echo "Usage: ${0##*/} [options]"
-	echo "    -p <pkg>           Build list or pkg [default: ${build_list_pkg}]"
-	echo "    -a <arch>          Arch [default: ${target_arch}]"
-	echo "    -b <branch>        Branch [default: ${target_branch}]"
-	echo '    -r <dir>           Chroots directory'
-	echo "                       [default: ${chroots_pkg}]"
-	echo '    -i <pkg>           Install a package into the working copy of the chroot'
-	echo '    -c                 Recreate chroot'
-	echo '    -w                 Clean up cache and sources'
-	echo '    -n                 Install and run namcap check'
-	echo '    -s                 Sign packages'
-	echo '    -u                 Udev base-devel group (no systemd)'
-	echo '    -q                 Query settings and pretend build'
-	echo '    -h                 This help'
-	echo ''
-	echo ''
-	exit $1
+    echo "Usage: ${0##*/} [options]"
+    echo "    -p <pkg>           Build list or pkg [default: ${build_list_pkg}]"
+    echo "    -a <arch>          Arch [default: ${target_arch}]"
+    echo "    -b <branch>        Branch [default: ${target_branch}]"
+    echo '    -r <dir>           Chroots directory'
+    echo "                       [default: ${chroots_pkg}]"
+    echo '    -i <pkg>           Install a package into the working copy of the chroot'
+    echo '    -c                 Recreate chroot'
+    echo '    -w                 Clean up cache and sources'
+    echo '    -n                 Install and run namcap check'
+    echo '    -s                 Sign packages'
+    echo '    -u                 Udev base-devel group (no systemd)'
+    echo '    -q                 Query settings and pretend build'
+    echo '    -h                 This help'
+    echo ''
+    echo ''
+    exit $1
 }
 
 orig_argv=("$@")
@@ -112,21 +112,21 @@ orig_argv=("$@")
 opts='p:a:b:r:i:cwnsuqh'
 
 while getopts "${opts}" arg; do
-	case "${arg}" in
-		p) build_list_pkg="$OPTARG" ;;
-		a) target_arch="$OPTARG" ;;
-		b) target_branch="$OPTARG" ;;
-		r) chroots_pkg="$OPTARG" ;;
-		i) install_pkgs+="$OPTARG"; mkchrootpkg_args+=(-I ${install_pkgs[*]}) ;;
-		c) clean_first=true ;;
-		w) wipe_clean=true ;;
-		n) namcap=true; mkchrootpkg_args+=(-n) ;;
-		s) sign=true ;;
-		u) udev_root=true ;;
-		q) pretend=true ;;
-		h|?) usage 0 ;;
-		*) echo "invalid argument '${arg}'"; usage 1 ;;
-	esac
+    case "${arg}" in
+        p) build_list_pkg="$OPTARG" ;;
+        a) target_arch="$OPTARG" ;;
+        b) target_branch="$OPTARG" ;;
+        r) chroots_pkg="$OPTARG" ;;
+        i) install_pkgs+="$OPTARG"; mkchrootpkg_args+=(-I ${install_pkgs[*]}) ;;
+        c) clean_first=true ;;
+        w) wipe_clean=true ;;
+        n) namcap=true; mkchrootpkg_args+=(-n) ;;
+        s) sign=true ;;
+        u) udev_root=true ;;
+        q) pretend=true ;;
+        h|?) usage 0 ;;
+        *) echo "invalid argument '${arg}'"; usage 1 ;;
+    esac
 done
 
 shift $(($OPTIND - 1))
diff --git a/bin/buildtree.in b/bin/buildtree.in
--- a/bin/buildtree.in
+++ b/bin/buildtree.in
@@ -19,19 +19,19 @@ import ${LIBDIR}/util.sh
 import ${LIBDIR}/util-pkgtree.sh
 
 display_settings(){
-	show_version
-	show_config
+    show_version
+    show_config
 
-	msg "ARGS:"
-	msg2 "sync: %s" "${sync}"
-	msg2 "abs: %s" "${abs}"
-	msg2 "clean: %s" "${clean}"
+    msg "ARGS:"
+    msg2 "sync: %s" "${sync}"
+    msg2 "abs: %s" "${abs}"
+    msg2 "clean: %s" "${clean}"
 
-	msg "PATHS:"
-	msg2 "tree_dir: %s" "${tree_dir}"
-	msg2 "repo_tree: %s" "${repo_tree[*]}"
-	msg2 "host_tree: %s" "${host_tree}"
-	msg2 "host_tree_abs: %s" "${host_tree_abs}"
+    msg "PATHS:"
+    msg2 "tree_dir: %s" "${tree_dir}"
+    msg2 "repo_tree: %s" "${repo_tree[*]}"
+    msg2 "host_tree: %s" "${host_tree}"
+    msg2 "host_tree_abs: %s" "${host_tree_abs}"
 }
 
 load_user_info
@@ -44,15 +44,15 @@ abs=false
 clean=false
 
 usage() {
-	echo "Usage: ${0##*/} [options]"
-	echo "    -s            Sync manjaro tree"
-	echo "    -a            Sync arch abs"
-	echo '    -c            Clean package tree'
-	echo '    -q            Query settings'
-	echo '    -h            This help'
-	echo ''
-	echo ''
-	exit $1
+    echo "Usage: ${0##*/} [options]"
+    echo "    -s            Sync manjaro tree"
+    echo "    -a            Sync arch abs"
+    echo '    -c            Clean package tree'
+    echo '    -q            Query settings'
+    echo '    -h            This help'
+    echo ''
+    echo ''
+    exit $1
 }
 
 orig_argv=("$@")
@@ -60,14 +60,14 @@ orig_argv=("$@")
 opts='sacqh'
 
 while getopts "${opts}" arg; do
-	case "${arg}" in
-		s) sync=true ;;
-		a) abs=true ;;
-		c) clean=true ;;
-		q) pretend=true ;;
-		h|?) usage 0 ;;
-		*) echo "invalid argument '${arg}'"; usage 1 ;;
-	esac
+    case "${arg}" in
+        s) sync=true ;;
+        a) abs=true ;;
+        c) clean=true ;;
+        q) pretend=true ;;
+        h|?) usage 0 ;;
+        *) echo "invalid argument '${arg}'"; usage 1 ;;
+    esac
 done
 
 shift $(($OPTIND - 1))
diff --git a/bin/check-yaml.in b/bin/check-yaml.in
--- a/bin/check-yaml.in
+++ b/bin/check-yaml.in
@@ -21,65 +21,65 @@ import ${LIBDIR}/util.sh
 import ${LIBDIR}/util-iso-yaml.sh
 
 show_profile(){
-	prepare_check "$1"
-	msg2 "yaml_dir: %s" "${yaml_dir}"
-	msg2 "nonfree_mhwd: %s" "${nonfree_mhwd}"
-	msg2 "autologin: %s" "${autologin}"
-	msg2 "nonfree_mhwd: %s" "${nonfree_mhwd}"
-	msg2 "pxe_boot: %s" "${pxe_boot}"
-	msg2 "plymouth_boot: %s" "${plymouth_boot}"
-	${plymouth_boot} && msg2 "plymouth_theme: %s" "${plymouth_theme}"
+    prepare_check "$1"
+    msg2 "yaml_dir: %s" "${yaml_dir}"
+    msg2 "nonfree_mhwd: %s" "${nonfree_mhwd}"
+    msg2 "autologin: %s" "${autologin}"
+    msg2 "nonfree_mhwd: %s" "${nonfree_mhwd}"
+    msg2 "pxe_boot: %s" "${pxe_boot}"
+    msg2 "plymouth_boot: %s" "${plymouth_boot}"
+    ${plymouth_boot} && msg2 "plymouth_theme: %s" "${plymouth_theme}"
 
-	[[ ${target_arch} == 'x86_64' ]] && msg2 "multilib: %s" "${multilib}"
+    [[ ${target_arch} == 'x86_64' ]] && msg2 "multilib: %s" "${multilib}"
 
-	msg2 "netinstall: %s" "${netinstall}"
-	${netinstall} && msg2 "netgroups: %s" "$(get_yaml)"
-	msg2 "unpackfs: %s" "${unpackfs}"
+    msg2 "netinstall: %s" "${netinstall}"
+    ${netinstall} && msg2 "netgroups: %s" "$(get_yaml)"
+    msg2 "unpackfs: %s" "${unpackfs}"
 
-	msg2 "efi_boot_loader: %s" "${efi_boot_loader}"
+    msg2 "efi_boot_loader: %s" "${efi_boot_loader}"
 
-	msg2 "hostname: %s" "${hostname}"
-	msg2 "username: %s" "${username}"
-	msg2 "password: %s" "${password}"
-	msg2 "login_shell: %s" "${login_shell}"
-	msg2 "addgroups: %s" "${addgroups}"
+    msg2 "hostname: %s" "${hostname}"
+    msg2 "username: %s" "${username}"
+    msg2 "password: %s" "${password}"
+    msg2 "login_shell: %s" "${login_shell}"
+    msg2 "addgroups: %s" "${addgroups}"
 
-	if [[ ${initsys} == 'systemd' ]];then
-		msg2 "enable_systemd: %s" "${enable_systemd[*]}"
-		msg2 "enable_systemd_live: %s" "${enable_systemd_live[*]}"
-		[[ -n ${disable_systemd[*]} ]] && msg2 "disable_systemd: %s" "${disable_systemd[*]}"
-	else
-		msg2 "enable_openrc: %s" "${enable_openrc[*]}"
-		msg2 "enable_openrc_live: %s" "${enable_openrc_live[*]}"
-		[[ -n ${disable_openrc[*]} ]] && msg2 "disable_openrc: %s" "${disable_openrc[*]}"
-	fi
+    if [[ ${initsys} == 'systemd' ]];then
+        msg2 "enable_systemd: %s" "${enable_systemd[*]}"
+        msg2 "enable_systemd_live: %s" "${enable_systemd_live[*]}"
+        [[ -n ${disable_systemd[*]} ]] && msg2 "disable_systemd: %s" "${disable_systemd[*]}"
+    else
+        msg2 "enable_openrc: %s" "${enable_openrc[*]}"
+        msg2 "enable_openrc_live: %s" "${enable_openrc_live[*]}"
+        [[ -n ${disable_openrc[*]} ]] && msg2 "disable_openrc: %s" "${disable_openrc[*]}"
+    fi
 
-	reset_profile
-	unset yaml_dir
+    reset_profile
+    unset yaml_dir
 }
 
 display_settings(){
-	show_version
-	show_config
+    show_version
+    show_config
 
-	msg "PROFILE:"
-	msg2 "list_dir_iso: %s" "${list_dir_iso}"
-	msg2 "build_lists: %s" "$(show_build_lists ${list_dir_iso})"
-	msg2 "build_list_iso: %s" "${build_list_iso}"
-	msg2 "is_build_list: %s" "${is_build_list}"
-	msg2 "build_mirror: %s" "${build_mirror}/${target_branch}"
-	${verbose} && msg2 "run_dir: %s" "${run_dir}"
+    msg "PROFILE:"
+    msg2 "list_dir_iso: %s" "${list_dir_iso}"
+    msg2 "build_lists: %s" "$(show_build_lists ${list_dir_iso})"
+    msg2 "build_list_iso: %s" "${build_list_iso}"
+    msg2 "is_build_list: %s" "${is_build_list}"
+    msg2 "build_mirror: %s" "${build_mirror}/${target_branch}"
+    ${verbose} && msg2 "run_dir: %s" "${run_dir}"
 
-	msg "OPTIONS:"
-	msg2 "arch: %s" "${target_arch}"
-	msg2 "initsys: %s" "${initsys}"
-	msg2 "kernel: %s" "${kernel}"
+    msg "OPTIONS:"
+    msg2 "arch: %s" "${target_arch}"
+    msg2 "initsys: %s" "${initsys}"
+    msg2 "kernel: %s" "${kernel}"
 
-	msg "ARGS:"
-	msg2 "calamares: %s" "${calamares}"
+    msg "ARGS:"
+    msg2 "calamares: %s" "${calamares}"
 
-	msg "CHECK QUEUE:"
-	run show_profile "${build_list_iso}"
+    msg "CHECK QUEUE:"
+    run show_profile "${build_list_iso}"
 }
 
 load_user_info
@@ -97,17 +97,17 @@ group=false
 cache_dir_netinstall="${cache_dir}/netinstall"
 
 usage() {
-	echo "Usage: ${0##*/} [options]"
-	echo "    -p <profile>       Buildset or profile [default: ${build_list_iso}]"
-	echo "    -a <arch>          Arch [default: ${target_arch}]"
-	echo "    -k <name>          Kernel to use[default: ${kernel}]"
-	echo "    -i <name>          Init system to use [default: ${initsys}]"
-	echo '    -c                 Check also calamares yaml files generated for the profile'
-	echo '    -q                 Query settings'
-	echo '    -h                 This help'
-	echo ''
-	echo ''
-	exit $1
+    echo "Usage: ${0##*/} [options]"
+    echo "    -p <profile>       Buildset or profile [default: ${build_list_iso}]"
+    echo "    -a <arch>          Arch [default: ${target_arch}]"
+    echo "    -k <name>          Kernel to use[default: ${kernel}]"
+    echo "    -i <name>          Init system to use [default: ${initsys}]"
+    echo '    -c                 Check also calamares yaml files generated for the profile'
+    echo '    -q                 Query settings'
+    echo '    -h                 This help'
+    echo ''
+    echo ''
+    exit $1
 }
 
 orig_argv=("$@")
@@ -115,17 +115,17 @@ orig_argv=("$@")
 opts='p:a:i:k:gcqh'
 
 while getopts "${opts}" arg; do
-	case "${arg}" in
-		p) build_list_iso="$OPTARG" ;;
-		a) target_arch="$OPTARG" ;;
-		i) initsys="$OPTARG" ;;
-		k) kernel="$OPTARG" ;;
-		c) calamares=true ;;
-		g) group=true ;;
-		q) pretend=true ;;
-		h|?) usage 0 ;;
-		*) echo "invalid argument '${arg}'"; usage 1 ;;
-	esac
+    case "${arg}" in
+        p) build_list_iso="$OPTARG" ;;
+        a) target_arch="$OPTARG" ;;
+        i) initsys="$OPTARG" ;;
+        k) kernel="$OPTARG" ;;
+        c) calamares=true ;;
+        g) group=true ;;
+        q) pretend=true ;;
+        h|?) usage 0 ;;
+        *) echo "invalid argument '${arg}'"; usage 1 ;;
+    esac
 done
 
 shift $(($OPTIND - 1))
diff --git a/bin/fstabgen.in b/bin/fstabgen.in
--- a/bin/fstabgen.in
+++ b/bin/fstabgen.in
@@ -20,73 +20,73 @@ LIBDIR='@libdir@'
 import ${LIBDIR}/util-fstab.sh
 
 write_source() {
-  local src=$1 spec= label= uuid= comment=()
+local src=$1 spec= label= uuid= comment=()
 
-  label=$(lsblk -rno LABEL "$1" 2>/dev/null)
-  uuid=$(lsblk -rno UUID "$1" 2>/dev/null)
+label=$(lsblk -rno LABEL "$1" 2>/dev/null)
+uuid=$(lsblk -rno UUID "$1" 2>/dev/null)
 
-  # bind mounts do not have a UUID!
+# bind mounts do not have a UUID!
 
-  case $bytag in
+case $bytag in
     '')
-      [[ $uuid ]] && comment=("UUID=$uuid")
-      [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
-      ;;
+    [[ $uuid ]] && comment=("UUID=$uuid")
+    [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
+    ;;
     LABEL)
-      spec=$label
-      [[ $uuid ]] && comment=("$src" "UUID=$uuid")
-      ;;
+    spec=$label
+    [[ $uuid ]] && comment=("$src" "UUID=$uuid")
+    ;;
     UUID)
-      spec=$uuid
-      comment=("$src")
-      [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
-      ;;
+    spec=$uuid
+    comment=("$src")
+    [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
+    ;;
     *)
-      [[ $uuid ]] && comment=("$1" "UUID=$uuid")
-      [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
-      [[ $bytag ]] && spec=$(lsblk -rno "$bytag" "$1" 2>/dev/null)
-      ;;
-  esac
+    [[ $uuid ]] && comment=("$1" "UUID=$uuid")
+    [[ $label ]] && comment+=("LABEL=$(mangle "$label")")
+    [[ $bytag ]] && spec=$(lsblk -rno "$bytag" "$1" 2>/dev/null)
+    ;;
+esac
 
-  [[ $comment ]] && printf '# %s\n' "${comment[*]}"
+[[ $comment ]] && printf '# %s\n' "${comment[*]}"
 
-  if [[ $spec ]]; then
+if [[ $spec ]]; then
     printf '%-20s' "$bytag=$(mangle "$spec")"
-  else
+else
     printf '%-20s' "$(mangle "$src")"
-  fi
+fi
 }
 
 optstring_apply_quirks() {
-  local varname=$1 fstype=$2
+local varname=$1 fstype=$2
 
-  # SELinux displays a 'seclabel' option in /proc/self/mountinfo. We can't know
-  # if the system we're generating the fstab for has any support for SELinux (as
-  # one might install Arch from a Fedora environment), so let's remove it.
-  optstring_remove_option "$varname" seclabel
+# SELinux displays a 'seclabel' option in /proc/self/mountinfo. We can't know
+# if the system we're generating the fstab for has any support for SELinux (as
+# one might install Arch from a Fedora environment), so let's remove it.
+optstring_remove_option "$varname" seclabel
 
-  case $fstype in
+case $fstype in
     f2fs)
-      # These are Kconfig options for f2fs. Kernels supporting the options will
-      # only provide the negative versions of these (e.g. noacl), and vice versa
-      # for kernels without support.
-      optstring_remove_option "$varname" noacl,acl,nouser_xattr,user_xattr
-      ;;
+    # These are Kconfig options for f2fs. Kernels supporting the options will
+    # only provide the negative versions of these (e.g. noacl), and vice versa
+    # for kernels without support.
+    optstring_remove_option "$varname" noacl,acl,nouser_xattr,user_xattr
+    ;;
     vfat)
-      # Before Linux v3.8, "cp" is prepended to the value of the codepage.
-      if optstring_get_option "$varname" codepage && [[ $codepage = cp* ]]; then
+    # Before Linux v3.8, "cp" is prepended to the value of the codepage.
+    if optstring_get_option "$varname" codepage && [[ $codepage = cp* ]]; then
         optstring_remove_option "$varname" codepage
         optstring_append_option "$varname" "codepage=${codepage#cp}"
-      fi
-      ;;
-  esac
+    fi
+    ;;
+esac
 }
 
 usage() {
-  cat <<EOF
+cat <<EOF
 usage: ${0##*/} [options] root
 
-  Options:
+Options:
     -L             Use labels for source identifiers (shortcut for -t LABEL)
     -p             Exclude pseudofs mounts (default behavior)
     -P             Include printing mounts
@@ -102,34 +102,34 @@ EOF
 }
 
 if [[ -z $1 || $1 = @(-h|--help) ]]; then
-  usage
-  exit $(( $# ? 0 : 1 ))
+usage
+exit $(( $# ? 0 : 1 ))
 fi
 
 while getopts ':LPpt:U' flag; do
-  case $flag in
+case $flag in
     L)
-      bytag=LABEL
-      ;;
+    bytag=LABEL
+    ;;
     U)
-      bytag=UUID
-      ;;
+    bytag=UUID
+    ;;
     P)
-      pseudofs=1
-      ;;
+    pseudofs=1
+    ;;
     p)
-      pseudofs=0
-      ;;
+    pseudofs=0
+    ;;
     t)
-      bytag=${OPTARG^^}
-      ;;
+    bytag=${OPTARG^^}
+    ;;
     :)
-      die '%s: option requires an argument -- '\''%s'\' "${0##*/}" "$OPTARG"
-      ;;
+    die '%s: option requires an argument -- '\''%s'\' "${0##*/}" "$OPTARG"
+    ;;
     ?)
-      die '%s: invalid option -- '\''%s'\' "${0##*/}" "$OPTARG"
-      ;;
-  esac
+    die '%s: invalid option -- '\''%s'\' "${0##*/}" "$OPTARG"
+    ;;
+esac
 done
 shift $(( OPTIND - 1 ))
 
@@ -137,100 +137,100 @@ shift $(( OPTIND - 1 ))
 root=$1; shift
 
 if ! mountpoint -q "$root"; then
-  die "$root is not a mountpoint"
+die "$root is not a mountpoint"
 fi
 
 # handle block devices
 findmnt -Recvruno SOURCE,TARGET,FSTYPE,OPTIONS,FSROOT "$root" |
     while read -r src target fstype opts fsroot; do
-  if (( !pseudofs )) && fstype_is_pseudofs "$fstype"; then
+if (( !pseudofs )) && fstype_is_pseudofs "$fstype"; then
     continue
-  fi
+fi
 
-  # default 5th and 6th columns
-  dump=0 pass=2
+# default 5th and 6th columns
+dump=0 pass=2
 
-  src=$(unmangle "$src")
-  target=$(unmangle "$target")
-  target=${target#$root}
+src=$(unmangle "$src")
+target=$(unmangle "$target")
+target=${target#$root}
 
-  if (( !foundroot )) && findmnt "$src" "$root" >/dev/null; then
+if (( !foundroot )) && findmnt "$src" "$root" >/dev/null; then
     # this is root. we can't possibly have more than one...
     pass=1 foundroot=1
-  fi
+fi
 
-  # if there's no fsck tool available, then only pass=0 makes sense.
-  if ! fstype_has_fsck "$fstype"; then
+# if there's no fsck tool available, then only pass=0 makes sense.
+if ! fstype_has_fsck "$fstype"; then
     pass=0
-  fi
+fi
 
-  if [[ $fsroot != / ]]; then
+if [[ $fsroot != / ]]; then
     if [[ $fstype = btrfs ]]; then
-      opts+=,subvol=${fsroot#/}
+    opts+=,subvol=${fsroot#/}
     else
-      # it's a bind mount
-      src=$(findmnt -funcevo TARGET "$src")$fsroot
-      if [[ $src -ef $target ]]; then
+    # it's a bind mount
+    src=$(findmnt -funcevo TARGET "$src")$fsroot
+    if [[ $src -ef $target ]]; then
         # hrmm, this is weird. we're probably looking at a file or directory
         # that was bound into a chroot from the host machine. Ignore it,
         # because this won't actually be a valid mount. Worst case, the user
         # just re-adds it.
         continue
-      fi
-      fstype=none
-      opts+=,bind
-      pass=0
     fi
-  fi
+    fstype=none
+    opts+=,bind
+    pass=0
+    fi
+fi
 
-  # filesystem quirks
-  case $fstype in
+# filesystem quirks
+case $fstype in
     fuseblk)
-      # well-behaved FUSE filesystems will report themselves as fuse.$fstype.
-      # this is probably NTFS-3g, but let's just make sure.
-      if ! newtype=$(lsblk -no FSTYPE "$src") || [[ -z $newtype ]]; then
+    # well-behaved FUSE filesystems will report themselves as fuse.$fstype.
+    # this is probably NTFS-3g, but let's just make sure.
+    if ! newtype=$(lsblk -no FSTYPE "$src") || [[ -z $newtype ]]; then
         # avoid blanking out fstype, leading to an invalid fstab
         error 'Failed to derive real filesystem type for FUSE device on %s' "$target"
-      else
+    else
         fstype=$newtype
-      fi
-      ;;
-  esac
+    fi
+    ;;
+esac
 
-  optstring_apply_quirks "opts" "$fstype"
+optstring_apply_quirks "opts" "$fstype"
 
-  # write one line
-  write_source "$src"
-  printf '\t%-10s' "/$(mangle "${target#/}")" "$fstype" "$opts"
-  printf '\t%s %s' "$dump" "$pass"
-  printf '\n\n'
+# write one line
+write_source "$src"
+printf '\t%-10s' "/$(mangle "${target#/}")" "$fstype" "$opts"
+printf '\t%s %s' "$dump" "$pass"
+printf '\n\n'
 done
 
 # handle swaps devices
 {
-  # ignore header
-  read
+# ignore header
+read
 
-  while read -r device type _ _ prio; do
+while read -r device type _ _ prio; do
     options=defaults
     if [[ $prio != -1 ]]; then
-      options+=,pri=$prio
+    options+=,pri=$prio
     fi
 
     # skip files marked deleted by the kernel
     [[ $device = *'\040(deleted)' ]] && continue
 
     if [[ $type = file ]]; then
-      printf '%-20s' "$device"
+    printf '%-20s' "$device"
     elif [[ $device = /dev/dm-+([0-9]) ]]; then
-      # device mapper doesn't allow characters we need to worry
-      # about being mangled, and it does the escaping of dashes
-      # for us in sysfs.
-      write_source "$(dm_name_for_devnode "$device")"
+    # device mapper doesn't allow characters we need to worry
+    # about being mangled, and it does the escaping of dashes
+    # for us in sysfs.
+    write_source "$(dm_name_for_devnode "$device")"
     else
-      write_source "$(unmangle "$device")"
+    write_source "$(unmangle "$device")"
     fi
 
     printf '\t%-10s\t%-10s\t%-10s\t0 0\n\n' 'none' 'swap' "$options"
-  done
+done
 } </proc/swaps
diff --git a/bin/mkchrootpkg.in b/bin/mkchrootpkg.in
--- a/bin/mkchrootpkg.in
+++ b/bin/mkchrootpkg.in
@@ -72,14 +72,14 @@ orig_argv=("$@")
 
 while getopts 'hcur:I:l:nT' arg; do
     case "$arg" in
-	c) clean_first=true ;;
-	u) update_first=true ;;
-	r) passeddir="$OPTARG" ;;
-	I) install_pkgs+=("$OPTARG") ;;
-	l) copy="$OPTARG" ;;
-	n) run_namcap=true; makepkg_args+=(-i) ;;
-	T) temp_chroot=true; copy+="-$$" ;;
-	h|*) usage ;;
+    c) clean_first=true ;;
+    u) update_first=true ;;
+    r) passeddir="$OPTARG" ;;
+    I) install_pkgs+=("$OPTARG") ;;
+    l) copy="$OPTARG" ;;
+    n) run_namcap=true; makepkg_args+=(-i) ;;
+    T) temp_chroot=true; copy+="-$$" ;;
+    h|*) usage ;;
     esac
 done
 
@@ -96,9 +96,9 @@ chrootdir=$(readlink -e "$passeddir")
 chroottype=$(stat -f -c %T "$chrootdir")
 
 if [[ ${copy:0:1} = / ]]; then
-	copydir=$copy
+    copydir=$copy
 else
-	copydir="$chrootdir/$copy"
+    copydir="$chrootdir/$copy"
 fi
 
 # Pass all arguments after -- right to makepkg
@@ -107,10 +107,10 @@ makepkg_args+=("${@:$OPTIND}")
 # See if -R was passed to makepkg
 for arg in "${@:OPTIND}"; do
     case ${arg%%=*} in
-	-*R*|--repackage)
-	    repack=true
-	    break 2
-	;;
+    -*R*|--repackage)
+        repack=true
+        break 2
+    ;;
     esac
 done
 
@@ -119,174 +119,174 @@ load_user_info
 # {{{ functions
 
 create_chroot() {
-	# Lock the chroot we want to use. We'll keep this lock until we exit.
-	lock 9 "$copydir.lock" "Locking chroot copy [$copy]"
+    # Lock the chroot we want to use. We'll keep this lock until we exit.
+    lock 9 "$copydir.lock" "Locking chroot copy [$copy]"
 
-	if [[ ! -d $copydir ]] || $clean_first; then
-		# Get a read lock on the root chroot to make
-		# sure we don't clone a half-updated chroot
-		slock 8 "$chrootdir/root.lock" "Locking clean chroot"
+    if [[ ! -d $copydir ]] || $clean_first; then
+        # Get a read lock on the root chroot to make
+        # sure we don't clone a half-updated chroot
+        slock 8 "$chrootdir/root.lock" "Locking clean chroot"
 
-		stat_busy "Creating clean working copy [$copy]"
-		if [[ "$chroottype" == btrfs ]] && ! mountpoint -q "$copydir"; then
-			if [[ -d $copydir ]]; then
-				btrfs subvolume delete "$copydir" >/dev/null ||
-					die "Unable to delete subvolume %s" "$copydir"
-			fi
-			btrfs subvolume snapshot "$chrootdir/root" "$copydir" >/dev/null ||
-				die "Unable to create subvolume %s" "$copydir"
-		else
-			mkdir -p "$copydir"
-			rsync -a --delete -q -W -x "$chrootdir/root/" "$copydir"
-		fi
-		stat_done
+        stat_busy "Creating clean working copy [$copy]"
+        if [[ "$chroottype" == btrfs ]] && ! mountpoint -q "$copydir"; then
+            if [[ -d $copydir ]]; then
+                btrfs subvolume delete "$copydir" >/dev/null ||
+                    die "Unable to delete subvolume %s" "$copydir"
+            fi
+            btrfs subvolume snapshot "$chrootdir/root" "$copydir" >/dev/null ||
+                die "Unable to create subvolume %s" "$copydir"
+        else
+            mkdir -p "$copydir"
+            rsync -a --delete -q -W -x "$chrootdir/root/" "$copydir"
+        fi
+        stat_done
 
-		# Drop the read lock again
-		exec 8>&-
-	fi
+        # Drop the read lock again
+        exec 8>&-
+    fi
 
-	# Update mtime
-	touch "$copydir"
+    # Update mtime
+    touch "$copydir"
 }
 
 clean_temporary() {
-	stat_busy "Removing temporary copy [$copy]"
-	if [[ "$chroottype" == btrfs ]] && ! mountpoint -q "$copydir"; then
-		btrfs subvolume delete "$copydir" >/dev/null ||
-			die "Unable to delete subvolume %s" "$copydir"
-	else
-		# avoid change of filesystem in case of an umount failure
-		rm --recursive --force --one-file-system "$copydir" ||
-			die "Unable to delete %s" "$copydir"
-	fi
+    stat_busy "Removing temporary copy [$copy]"
+    if [[ "$chroottype" == btrfs ]] && ! mountpoint -q "$copydir"; then
+        btrfs subvolume delete "$copydir" >/dev/null ||
+            die "Unable to delete subvolume %s" "$copydir"
+    else
+        # avoid change of filesystem in case of an umount failure
+        rm --recursive --force --one-file-system "$copydir" ||
+            die "Unable to delete %s" "$copydir"
+    fi
 
-	# remove lock file
-	rm -f "$copydir.lock"
-	stat_done
+    # remove lock file
+    rm -f "$copydir.lock"
+    stat_done
 }
 
 install_packages() {
-	local -a pkgnames
-	local ret
+    local -a pkgnames
+    local ret
 
-	pkgnames=("${install_pkgs[@]##*/}")
+    pkgnames=("${install_pkgs[@]##*/}")
 
-	cp -- "${install_pkgs[@]}" "$copydir/root/"
+    cp -- "${install_pkgs[@]}" "$copydir/root/"
 
-	chroot-run "$copydir" \
-			pacman -U --noconfirm -- "${pkgnames[@]/#//root/}"
-	ret=$?
-	rm -- "${pkgnames[@]/#/$copydir/root/}"
+    chroot-run "$copydir" \
+            pacman -U --noconfirm -- "${pkgnames[@]/#//root/}"
+    ret=$?
+    rm -- "${pkgnames[@]/#/$copydir/root/}"
 
-	# If there is no PKGBUILD we are done
-	[[ -f PKGBUILD ]] || exit $ret
+    # If there is no PKGBUILD we are done
+    [[ -f PKGBUILD ]] || exit $ret
 }
 
 prepare_chroot() {
-	$repack || rm -rf "$copydir/build"
+    $repack || rm -rf "$copydir/build"
 
-	local builduser_uid="${SUDO_UID:-$UID}"
-	local builduser_gid="$(id -g "$builduser_uid")"
-	local install="install -o $builduser_uid -g $builduser_gid"
-	local x
+    local builduser_uid="${SUDO_UID:-$UID}"
+    local builduser_gid="$(id -g "$builduser_uid")"
+    local install="install -o $builduser_uid -g $builduser_gid"
+    local x
 
-	# We can't use useradd without chrooting, otherwise it invokes PAM modules
-	# which we might not be able to load (i.e. when building i686 packages on
-	# an x86_64 host).
-	sed -e '/^builduser:/d' -i "$copydir"/etc/{passwd,group}
-	printf >>"$copydir/etc/group"  'builduser:x:%d:\n' $builduser_gid
-	printf >>"$copydir/etc/passwd" 'builduser:x:%d:%d:builduser:/build:/bin/bash\n' $builduser_uid $builduser_gid
+    # We can't use useradd without chrooting, otherwise it invokes PAM modules
+    # which we might not be able to load (i.e. when building i686 packages on
+    # an x86_64 host).
+    sed -e '/^builduser:/d' -i "$copydir"/etc/{passwd,group}
+    printf >>"$copydir/etc/group"  'builduser:x:%d:\n' $builduser_gid
+    printf >>"$copydir/etc/passwd" 'builduser:x:%d:%d:builduser:/build:/bin/bash\n' $builduser_uid $builduser_gid
 
-	$install -d "$copydir"/{build,build/.gnupg,startdir,{pkg,srcpkg,src,log}dest}
+    $install -d "$copydir"/{build,build/.gnupg,startdir,{pkg,srcpkg,src,log}dest}
 
-	for x in .gnupg/pubring.{kbx,gpg}; do
-		[[ -r $USER_HOME/$x ]] || continue
-		$install -m 644 "$USER_HOME/$x" "$copydir/build/$x"
-	done
+    for x in .gnupg/pubring.{kbx,gpg}; do
+        [[ -r $USER_HOME/$x ]] || continue
+        $install -m 644 "$USER_HOME/$x" "$copydir/build/$x"
+    done
 
-	sed -e '/^MAKEFLAGS=/d' -e '/^PACKAGER=/d' -i "$copydir/etc/makepkg.conf"
-	for x in BUILDDIR=/build PKGDEST=/pkgdest SRCPKGDEST=/srcpkgdest SRCDEST=/srcdest LOGDEST=/logdest \
-		"MAKEFLAGS='$MAKEFLAGS'" "PACKAGER='$PACKAGER'"
-	do
-		grep -q "^$x" "$copydir/etc/makepkg.conf" && continue
-		echo "$x" >>"$copydir/etc/makepkg.conf"
-	done
+    sed -e '/^MAKEFLAGS=/d' -e '/^PACKAGER=/d' -i "$copydir/etc/makepkg.conf"
+    for x in BUILDDIR=/build PKGDEST=/pkgdest SRCPKGDEST=/srcpkgdest SRCDEST=/srcdest LOGDEST=/logdest \
+        "MAKEFLAGS='$MAKEFLAGS'" "PACKAGER='$PACKAGER'"
+    do
+        grep -q "^$x" "$copydir/etc/makepkg.conf" && continue
+        echo "$x" >>"$copydir/etc/makepkg.conf"
+    done
 
-	cat > "$copydir/etc/sudoers.d/builduser-pacman" <<EOF
+    cat > "$copydir/etc/sudoers.d/builduser-pacman" <<EOF
 Defaults env_keep += "HOME"
 builduser ALL = NOPASSWD: /usr/bin/pacman
 EOF
-	chmod 440 "$copydir/etc/sudoers.d/builduser-pacman"
+    chmod 440 "$copydir/etc/sudoers.d/builduser-pacman"
 
-	# This is a little gross, but this way the script is recreated every time in the
-	# working copy
-	{
-		printf '#!/bin/bash\n'
-		declare -f _chrootbuild
-		printf '_chrootbuild'
-		printf ' %q' "${makepkg_args[@]}"
-		printf ' || exit\n'
+    # This is a little gross, but this way the script is recreated every time in the
+    # working copy
+    {
+        printf '#!/bin/bash\n'
+        declare -f _chrootbuild
+        printf '_chrootbuild'
+        printf ' %q' "${makepkg_args[@]}"
+        printf ' || exit\n'
 
-		if $run_namcap; then
-			declare -f _chrootnamcap
-			printf '_chrootnamcap || exit\n'
-		fi
-	} >"$copydir/chrootbuild"
-	chmod +x "$copydir/chrootbuild"
+        if $run_namcap; then
+            declare -f _chrootnamcap
+            printf '_chrootnamcap || exit\n'
+        fi
+    } >"$copydir/chrootbuild"
+    chmod +x "$copydir/chrootbuild"
 }
 
 # These functions aren't run in makechrootpkg,
 # so no global variables
 _chrootbuild() {
-	. /etc/profile
-	export HOME=/build
-	cd /startdir
-	sudo -u builduser makepkg "$@"
+    . /etc/profile
+    export HOME=/build
+    cd /startdir
+    sudo -u builduser makepkg "$@"
 }
 
 _chrootnamcap() {
-	pacman -S --needed --noconfirm namcap
-	for pkgfile in /startdir/PKGBUILD /pkgdest/*; do
-		echo "Checking ${pkgfile##*/}"
-		sudo -u builduser namcap "$pkgfile" 2>&1 | tee "/logdest/${pkgfile##*/}-namcap.log"
-	done
+    pacman -S --needed --noconfirm namcap
+    for pkgfile in /startdir/PKGBUILD /pkgdest/*; do
+        echo "Checking ${pkgfile##*/}"
+        sudo -u builduser namcap "$pkgfile" 2>&1 | tee "/logdest/${pkgfile##*/}-namcap.log"
+    done
 }
 
 download_sources() {
-	local builddir="$(mktemp -d)"
-	chmod 1777 "$builddir"
+    local builddir="$(mktemp -d)"
+    chmod 1777 "$builddir"
 
-	# Ensure sources are downloaded
-	if [[ -n $SUDO_USER ]]; then
-		sudo -u $SUDO_USER env SRCDEST="$SRCDEST" BUILDDIR="$builddir" \
-			makepkg --config="$copydir/etc/makepkg.conf" --verifysource -o
-	else
-		( export SRCDEST BUILDDIR="$builddir"
-			makepkg --asroot --config="$copydir/etc/makepkg.conf" --verifysource -o
-		)
-	fi
-	(( $? != 0 )) && die "Could not download sources."
+    # Ensure sources are downloaded
+    if [[ -n $SUDO_USER ]]; then
+        sudo -u $SUDO_USER env SRCDEST="$SRCDEST" BUILDDIR="$builddir" \
+            makepkg --config="$copydir/etc/makepkg.conf" --verifysource -o
+    else
+        ( export SRCDEST BUILDDIR="$builddir"
+            makepkg --asroot --config="$copydir/etc/makepkg.conf" --verifysource -o
+        )
+    fi
+    (( $? != 0 )) && die "Could not download sources."
 
-	# Clean up garbage from verifysource
-	rm -rf $builddir
+    # Clean up garbage from verifysource
+    rm -rf $builddir
 }
 
 move_products() {
-	for pkgfile in "$copydir"/pkgdest/*; do
-		chown "$src_owner" "$pkgfile"
-		mv "$pkgfile" "$PKGDEST"
-	done
+    for pkgfile in "$copydir"/pkgdest/*; do
+        chown "$src_owner" "$pkgfile"
+        mv "$pkgfile" "$PKGDEST"
+    done
 
-	for l in "$copydir"/logdest/*; do
-		[[ $l == */logpipe.* ]] && continue
-		chown "$src_owner" "$l"
-		mv "$l" "$LOGDEST"
-	done
+    for l in "$copydir"/logdest/*; do
+        [[ $l == */logpipe.* ]] && continue
+        chown "$src_owner" "$l"
+        mv "$l" "$LOGDEST"
+    done
 
-	for s in "$copydir"/srcpkgdest/*; do
-		chown "$src_owner" "$s"
-		mv "$s" "$SRCPKGDEST"
-	done
+    for s in "$copydir"/srcpkgdest/*; do
+        chown "$src_owner" "$s"
+        mv "$s" "$SRCPKGDEST"
+    done
 }
 # }}}
 
@@ -303,10 +303,10 @@ load_vars "$USER_HOME/.makepkg.conf" || load_vars /etc/makepkg.conf
 create_chroot
 
 $update_first && chroot-run \
-		  -r "${mountargs_ro}" \
-		  -w "${mountargs_rw}" \
-		  "$copydir" \
-		  pacman -Syu --noconfirm
+        -r "${mountargs_ro}" \
+        -w "${mountargs_rw}" \
+        "$copydir" \
+        pacman -Syu --noconfirm
 
 [[ -n ${install_pkgs[*]} ]] && install_packages
 
@@ -317,22 +317,22 @@ prepare_chroot
 mountargs_rw="${PWD}:/startdir,${SRCDEST}:/srcdest"
 
 if chroot-run -r "${mountargs_ro}" \
-	      -w "${mountargs_rw}" \
-	      "$copydir" \
-	      /chrootbuild; then
-	move_products
+        -w "${mountargs_rw}" \
+        "$copydir" \
+        /chrootbuild; then
+    move_products
 else
-	(( ret += 1 ))
+    (( ret += 1 ))
 fi
 
 $temp_chroot && clean_temporary
 
 if (( ret != 0 )); then
-	if $temp_chroot; then
-		die "Build failed"
-	else
-		die "Build failed, check %s/build" "$copydir"
-	fi
+    if $temp_chroot; then
+        die "Build failed"
+    else
+        die "Build failed, check %s/build" "$copydir"
+    fi
 else
-	true
+    true
 fi
