[checkpkg] format code

diff --git a/bin/checkpkg.in b/bin/checkpkg.in
--- a/bin/checkpkg.in
+++ b/bin/checkpkg.in
@@ -20,7 +20,7 @@ load_vars "$HOME/.makepkg.conf"
 load_vars /etc/makepkg.conf
 
 if [[ ! -f PKGBUILD ]]; then
-    die 'This must be run in the directory of a built package.'
+	die 'This must be run in the directory of a built package.'
 fi
 
 . ./PKGBUILD
@@ -32,46 +32,46 @@ STARTDIR=$(pwd)
 TEMPDIR=$(mktemp -d --tmpdir checkpkg-script.XXXX)
 
 for _pkgname in "${pkgname[@]}"; do
-    target_pkgver=$(get_full_version "$_pkgname")
-    if ! pkgfile=$(find_cached_package "$_pkgname" "$target_pkgver" "$CARCH"); then
-	die 'tarball not found for package: %s' "${_pkgname}-$target_pkgver"
-    fi
+	target_pkgver=$(get_full_version "$_pkgname")
+	if ! pkgfile=$(find_cached_package "$_pkgname" "$target_pkgver" "$CARCH"); then
+		die 'tarball not found for package: %s' "${_pkgname}-$target_pkgver"
+	fi
 
-    ln -s "$pkgfile" "$TEMPDIR"
+	ln -s "$pkgfile" "$TEMPDIR"
 
-    pkgurl=$(pacman -Spdd --print-format '%l' --noconfirm "$_pkgname")
+	pkgurl=$(pacman -Spdd --print-format '%l' --noconfirm "$_pkgname")
 
-    if [[ $? -ne 0 ]]; then
-	die "Couldn't download previous package for %s." "$_pkgname"
-    fi
+	if [[ $? -ne 0 ]]; then
+		die "Couldn't download previous package for %s." "$_pkgname"
+	fi
 
-    oldpkg=${pkgurl##*://*/}
+	oldpkg=${pkgurl##*://*/}
 
-    if [[ ${oldpkg##*/} = ${pkgfile##*/} ]]; then
-	die "The built package (%s) is the one in the repo right now!" "$_pkgname"
-    fi
+	if [[ ${oldpkg##*/} = ${pkgfile##*/} ]]; then
+		die "The built package (%s) is the one in the repo right now!" "$_pkgname"
+	fi
 
-    if [[ $pkgurl = file://* ]]; then
-	ln -s "${pkgurl#file://}" "$TEMPDIR/$oldpkg"
-    elif [[ -f "$PKGDEST/$oldpkg" ]]; then
-	ln -s "$PKGDEST/$oldpkg" "$TEMPDIR/$oldpkg"
-    elif [[ -f "$STARTDIR/$oldpkg" ]]; then
-	ln -s "$STARTDIR/$oldpkg" "$TEMPDIR/$oldpkg"
-    else
-	curl -fsLC - --retry 3 --retry-delay 3 -o "$TEMPDIR/$oldpkg" "$pkgurl"
-    fi
+	if [[ $pkgurl = file://* ]]; then
+		ln -s "${pkgurl#file://}" "$TEMPDIR/$oldpkg"
+	elif [[ -f "$PKGDEST/$oldpkg" ]]; then
+		ln -s "$PKGDEST/$oldpkg" "$TEMPDIR/$oldpkg"
+	elif [[ -f "$STARTDIR/$oldpkg" ]]; then
+		ln -s "$STARTDIR/$oldpkg" "$TEMPDIR/$oldpkg"
+	else
+		curl -fsLC - --retry 3 --retry-delay 3 -o "$TEMPDIR/$oldpkg" "$pkgurl"
+	fi
 
-    bsdtar tf "$TEMPDIR/$oldpkg" | sort > "$TEMPDIR/filelist-$_pkgname-old"
-    bsdtar tf "$pkgfile" | sort > "$TEMPDIR/filelist-$_pkgname"
+	bsdtar tf "$TEMPDIR/$oldpkg" | sort > "$TEMPDIR/filelist-$_pkgname-old"
+	bsdtar tf "$pkgfile" | sort > "$TEMPDIR/filelist-$_pkgname"
 
-    sdiff -s "$TEMPDIR/filelist-$_pkgname-old" "$TEMPDIR/filelist-$_pkgname"
+	sdiff -s "$TEMPDIR/filelist-$_pkgname-old" "$TEMPDIR/filelist-$_pkgname"
 
-    find-libprovides "$TEMPDIR/$oldpkg" 2>/dev/null | sort > "$TEMPDIR/libraries-$_pkgname-old"
-    find-libprovides "$pkgfile" 2>/dev/null | sort > "$TEMPDIR/libraries-$_pkgname"
-    if ! diff_output="$(sdiff -s "$TEMPDIR/libraries-$_pkgname-old" "$TEMPDIR/libraries-$_pkgname")"; then
-	msg "Sonames differ in $_pkgname!"
-	echo "$diff_output"
-    else
-	msg "No soname differences for $_pkgname."
-    fi
+	find-libprovides "$TEMPDIR/$oldpkg" 2>/dev/null | sort > "$TEMPDIR/libraries-$_pkgname-old"
+	find-libprovides "$pkgfile" 2>/dev/null | sort > "$TEMPDIR/libraries-$_pkgname"
+	if ! diff_output="$(sdiff -s "$TEMPDIR/libraries-$_pkgname-old" "$TEMPDIR/libraries-$_pkgname")"; then
+		msg "Sonames differ in $_pkgname!"
+		echo "$diff_output"
+	else
+		msg "No soname differences for $_pkgname."
+	fi
 done
