[manjaro-chroot] add experimental automount support

diff --git a/bin/manjaro-chroot.in b/bin/manjaro-chroot.in
--- a/bin/manjaro-chroot.in
+++ b/bin/manjaro-chroot.in
@@ -18,30 +18,44 @@ LIBDIR='@libdir@'
 [[ -r ${LIBDIR}/util-msg.sh ]] && source ${LIBDIR}/util-msg.sh
 
 import ${LIBDIR}/util-mount.sh
+import ${LIBDIR}/util.sh
+
+automount=false
 
 usage() {
-  cat <<EOF
-usage: ${0##*/} chroot-dir [command]
-
-    -h             Print this help message
-
-If 'command' is unspecified, ${0##*/} will launch /bin/sh.
-
-EOF
+	echo 'usage: ${0##*/} chroot-dir [command]'
+	echo '-a             Automount detected linux system'
+	echo '-h             Print this help message'
+	echo ''
+	echo "If 'command' is unspecified, ${0##*/} will launch /bin/sh."
+	exit $1
 }
 
-if [[ -z $1 || $1 = @(-h|--help) ]]; then
-  usage
-  exit $(( $# ? 0 : 1 ))
+orig_argv=("$@")
+
+opts=':ha'
+
+while getopts ${opts} arg; do
+	case "${arg}" in
+		a) automount=true ;;
+		*) echo "invalid argument ${arg}"; usage 1;;
+		h|?) usage 0 ;;
+	esac
+done
+shift $(( OPTIND - 1 ))
+
+check_root "$0" "${orig_argv[@]}"
+
+if ${automount};then
+	chrootdir=/mnt
+	chroot_mount_partitions
+else
+	chrootdir=$1
+	shift
 fi
 
-(( EUID == 0 )) || die 'This script must be run with root privileges'
-chrootdir=$1
-shift
-
 [[ -d $chrootdir ]] || die "Can't create chroot on non-directory %s" "$chrootdir"
-
 chroot_api_mount "$chrootdir" || die "failed to setup API filesystems in chroot %s" "$chrootdir"
 chroot_mount /etc/resolv.conf "$chrootdir/etc/resolv.conf" --bind
 
-SHELL=/bin/sh chroot "$chrootdir" "$@"
+SHELL=/bin/sh unshare --fork --pid chroot "$chrootdir" "$@"
