[mkchroot] reactivate error handling of basestrap call

diff --git a/bin/mkchroot.in b/bin/mkchroot.in
--- a/bin/mkchroot.in
+++ b/bin/mkchroot.in
@@ -88,10 +88,10 @@ if [[ -n $pac_conf ]] && [[ -n $mirrors_conf ]]; then
 	sed "s#Include = /etc/pacman.d/mirrorlist#Server = ${url}#g" $pac_conf > $pac_base
 
 	basestrap -GMcd ${pac_base:+-C "$pac_base"} "$working_dir" \
-	   "${cache_dirs[@]/#/--cachedir=}" "$@" #|| die 'Failed to install all packages'
+	   "${cache_dirs[@]/#/--cachedir=}" "$@" || die 'Failed to install all packages'
 else
 	basestrap -GMcd ${pac_conf:+-C "$pac_conf"} "$working_dir" \
-	   "${cache_dirs[@]/#/--cachedir=}" "$@" #|| die 'Failed to install all packages'
+	   "${cache_dirs[@]/#/--cachedir=}" "$@" || die 'Failed to install all packages'
 fi
 
 [[ -f "$pac_base" ]] && rm "$pac_base"
