buildiso, buildpkg: use nice new pacman-mirrors features to set chroot branch

diff --git a/bin/mkchroot.in b/bin/mkchroot.in
--- a/bin/mkchroot.in
+++ b/bin/mkchroot.in
@@ -25,6 +25,7 @@ build_locales=false
 keep_mirrors=false
 keep_flag=''
 nosetarch=false
+branch=stable
 
 usage() {
     echo "Usage: ${0##*/} [options] working-dir package-list..."
@@ -32,20 +33,18 @@ usage() {
     echo '    -C <file>     Location of a pacman config file'
     echo '    -M <file>     Location of a makepkg config file'
     echo '    -S <file>     Location of a pacman-mirrors config file'
+    echo '    -B <branch>   Set branch'
+    echo '    -U <url>      Set a specific mirror'
     echo '    -c <dir>      Set pacman cache'
     echo '    -f <file>     Copy file from the host to the chroot'
     echo '    -s            Do not run setarch'
-    echo '    -L            Use build locale.gen en/de'
-    echo '    -B            Use custom build mirror'
-    echo '    -K            Keep mirrorlist (-B)'
-    echo '    -x            copy pacman.conf'
     echo '    -h            This message'
     exit 1
 }
 
 orig_argv=("$0" "$@")
 
-opts='hLKC:M:S:c:B:f:s'
+opts='hC:M:S:c:f:s:U:B'
 
 while getopts ${opts} arg; do
     case "${arg}" in
@@ -55,9 +54,8 @@ while getopts ${opts} arg; do
         c) cache_dir="$OPTARG" ;;
         f) files+=("$OPTARG") ;;
         s) nosetarch=true ;;
-        L) build_locales=true ;;
-        B) build_mirror="$OPTARG" ;;
-        K) keep_mirrors=true; keep_flag='-K' ;;
+        B) branch="$OPTARG" ;;
+        U) mirror="$OPTARG" ;;
         h|?) usage ;;
         *) error "invalid argument '%s'" "$arg"; usage ;;
     esac
@@ -90,11 +88,11 @@ umask 0022
 lock 9 "${working_dir}.lock" "Locking chroot"
 
 if is_btrfs "$working_dir"; then
-	rmdir "$working_dir"
-	if ! btrfs subvolume create "$working_dir"; then
-		die "Couldn't create subvolume for '%s'" "$working_dir"
-	fi
-	chmod 0755 "$working_dir"
+    rmdir "$working_dir"
+    if ! btrfs subvolume create "$working_dir"; then
+        die "Couldn't create subvolume for '%s'" "$working_dir"
+    fi
+    chmod 0755 "$working_dir"
 fi
 
 for file in "${files[@]}"; do
@@ -102,44 +100,21 @@ for file in "${files[@]}"; do
     cp "$file" "$working_dir$file"
 done
 
-# Workaround when creating a chroot in a branch different of the host
-if [[ -n $pac_conf ]] && [[ -n $mirrors_conf ]] && [[ -n ${build_mirror} ]]; then
-    url=${build_mirror}'/$repo/$arch'
-    info "mirror: %s" "$url"
-    pac_base="$working_dir/pacman-basestrap.conf"
-    sed "s#Include = /etc/pacman.d/mirrorlist#Server = ${url}#g" $pac_conf > $pac_base
+basestrap_args=(-GMcd ${pac_conf:+-C "$pac_conf"} ${cache_dirs[@]/#/--cachedir=} -B ${branch:+-"$branch"} ${mirrors_conf:+-P "$mirrors_conf"})
 
-    _env=()
-    while read -r varname; do
-        _env+=("$varname=${!varname}")
-    done < <(declare -x | sed -r 's/^declare -x ([^=]*)=.*/\1/' | grep -i '_proxy$')
-    env -i "${_env[@]}" \
-    basestrap -GMcd ${pac_base:+-C "$pac_base"} "$working_dir" \
-    "${cache_dirs[@]/#/--cachedir=}" "$@" || die 'Failed to install all packages'
+[[ -n ${mirror} ]] && basestrap_args+=(-U "${mirror}")
 
-    [[ -f "$pac_base" ]] && rm "$pac_base"
-else
-    _env=()
-    while read -r varname; do
-        _env+=("$varname=${!varname}")
-    done < <(declare -x | sed -r 's/^declare -x ([^=]*)=.*/\1/' | grep -i '_proxy$')
-    env -i "${_env[@]}" \
-    basestrap -GMcd ${pac_conf:+-C "$pac_conf"} "$working_dir" \
-    "${cache_dirs[@]/#/--cachedir=}" "$@" || die 'Failed to install all packages'
-fi
+_env=()
+while read -r varname; do
+    _env+=("$varname=${!varname}")
+done < <(declare -x | sed -r 's/^declare -x ([^=]*)=.*/\1/' | grep -i '_proxy$')
+env -i "${_env[@]}" \
+
+basestrap "${basestrap_args[@]}" "$working_dir" "$@" || die 'Failed to install all packages'
 
 echo "$version" > "$working_dir/.manjaro-tools"
 
-if ${build_locales};then
-    info "Using build locales ..."
-    mv "$working_dir/etc/locale.gen" "$working_dir/etc/locale.gen.bak"
-    mv "$working_dir/etc/locale.conf" "$working_dir/etc/locale.conf.bak"
-    printf '%s.UTF-8 UTF-8\n' en_US > "$working_dir/etc/locale.gen"
-    printf 'LANG=%s.UTF-8\n' en_US > "$working_dir/etc/locale.conf"
-    printf 'LC_MESSAGES=C\n' >> "$working_dir/etc/locale.conf"
-fi
-
-chroot_args=(${pac_conf:+-C "$pac_conf"} ${makepkg_conf:+-M "$makepkg_conf"} ${mirrors_conf:+-S "$mirrors_conf"} ${build_mirror:+-B "$build_mirror"} ${cache_dir:+-c "$cache_dir"} ${keep_flag})
+chroot_args=(${pac_conf:+-C "$pac_conf"} ${makepkg_conf:+-M "$makepkg_conf"} ${cache_dir:+-c "$cache_dir"})
 ${nosetarch} && chroot_args+=(${nosetarch:+-s})
 
 exec chroot-run \
