Indentation Fixment in bin/mkchroot.in
Indentation Fixment in bin/mkchroot.in

diff --git a/bin/mkchroot.in b/bin/mkchroot.in
--- a/bin/mkchroot.in
+++ b/bin/mkchroot.in
@@ -90,11 +90,11 @@ umask 0022
 lock 9 "${working_dir}.lock" "Locking chroot"
 
 if is_btrfs "$working_dir"; then
-	rmdir "$working_dir"
-	if ! btrfs subvolume create "$working_dir"; then
-		die "Couldn't create subvolume for '%s'" "$working_dir"
-	fi
-	chmod 0755 "$working_dir"
+    rmdir "$working_dir"
+    if ! btrfs subvolume create "$working_dir"; then
+        die "Couldn't create subvolume for '%s'" "$working_dir"
+    fi
+    chmod 0755 "$working_dir"
 fi
 
 for file in "${files[@]}"; do
