Arch patch (#264)
* initial arch backport

* fix args

* chroot-run: remove commented code
mkchrootpkg: update help

* lib: nove lock functions to util-msg

* mkchrootpkg: fix namcap, should go upstream

diff --git a/bin/mkchrootpkg.in b/bin/mkchrootpkg.in
--- a/bin/mkchrootpkg.in
+++ b/bin/mkchrootpkg.in
@@ -19,138 +19,115 @@ import ${LIBDIR}/util.sh
 
 shopt -s nullglob
 
-makepkg_args=(-s --noconfirm -L)
-repack=false
-update_first=false
-clean_first=false
-install_pkg=
-run_namcap=false
-temp_chroot=false
-chrootdir=
-passeddir=
-declare -a install_pkgs
-declare -i ret=0
+init_variables() {
+    default_makepkg_args=(-s --noconfirm -L --holdver)
+    makepkg_args=("${default_makepkg_args[@]}")
+    repack=false
+    update_first=false
+    clean_first=false
+    run_namcap=false
+    temp_chroot=false
+    chrootdir=
+    passeddir=
+    makepkg_user=
+    declare -ga install_pkgs
+    declare -gi ret=0
 
-copy=$USER
-[[ -n $SUDO_USER ]] && copy=$SUDO_USER
-[[ -z "$copy" || $copy = root ]] && copy=copy
-src_owner=${SUDO_USER:-$USER}
+    bindmounts_ro=()
+    bindmounts_rw=()
+
+    copy=$USER
+    [[ -n ${SUDO_USER:-} ]] && copy=$SUDO_USER
+    [[ -z "$copy" || $copy = root ]] && copy=copy
+    src_owner=${SUDO_USER:-$USER}
+}
 
 usage() {
     echo "Usage: ${0##*/} [options] -r <chrootdir> [--] [makepkg args]"
-    echo '      Run this script in a PKGBUILD dir to build a package inside a'
-    echo '      clean chroot. Arguments passed to this script after the'
-    echo '      end-of-options marker (--) will be passed to makepkg.'
+    echo ' Run this script in a PKGBUILD dir to build a package inside a'
+    echo ' clean chroot. Arguments passed to this script after the'
+    echo ' end-of-options marker (--) will be passed to makepkg.'
     echo ''
-    echo '      The chroot dir consists of the following directories:'
-    echo '      <chrootdir>/{root, copy} but only "root" is required'
-    echo '      by default. The working copy will be created as needed'
+    echo ' The chroot dir consists of the following directories:'
+    echo ' <chrootdir>/{root, copy} but only "root" is required'
+    echo ' by default. The working copy will be created as needed'
     echo ''
-    echo '      The chroot "root" directory must be created via the following'
-    echo '      command:'
-    echo '      mkchroot <chrootdir>/root base-devel'
+    echo 'The chroot "root" directory must be created via the following'
+    echo 'command:'
+    echo '    mkarchroot <chrootdir>/root base-devel'
     echo ''
-    echo "      Default makepkg args: ${makepkg_args[*]}"
+    echo 'This script reads {SRC,SRCPKG,PKG,LOG}DEST, MAKEFLAGS and PACKAGER'
+    echo 'from makepkg.conf(5), if those variables are not part of the'
+    echo 'environment.'
     echo ''
-    echo '      Flags:'
-    echo '        -h         This help'
-    echo '        -c         Clean the chroot before building'
-    echo '        -u         Update the working copy of the chroot before building'
-    echo '                   This is useful for rebuilds without dirtying the pristine'
-    echo '                   chroot'
-    echo '        -r <dir>   The chroot dir to use'
-    echo '        -I <pkg>   Install a package into the working copy of the chroot'
-    echo '        -l <copy>  The directory to use as the working copy of the chroot'
-    echo '                   Useful for maintaining multiple copies'
-    echo "                   Default: $copy"
-    echo '        -n         Run namcap on the package'
-    echo '        -T         Build in a temporary directory'
+    echo "Default makepkg args: ${default_makepkg_args[*]}"
+    echo ''
+    echo 'Flags:'
+    echo '-h         This help'
+    echo '-c         Clean the chroot before building'
+    echo '-d <dir>   Bind directory into build chroot as read-write'
+    echo '-D <dir>   Bind directory into build chroot as read-only'
+    echo '-u         Update the working copy of the chroot before building'
+    echo '           This is useful for rebuilds without dirtying the pristine'
+    echo '           chroot'
+    echo '-r <dir>   The chroot dir to use'
+    echo '-I <pkg>   Install a package into the working copy of the chroot'
+    echo '-l <copy>  The directory to use as the working copy of the chroot'
+    echo '           Useful for maintaining multiple copies'
+    echo "           Default: $copy"
+    echo '-n         Run namcap on the package'
+    echo '-T         Build in a temporary directory'
+    echo '-U         Run makepkg as a specified user'
     exit 1
 }
 
-orig_argv=("$@")
-
-while getopts 'hcur:I:l:nT' arg; do
-    case "$arg" in
-    c) clean_first=true ;;
-    u) update_first=true ;;
-    r) passeddir="$OPTARG" ;;
-    I) install_pkgs+=("$OPTARG") ;;
-    l) copy="$OPTARG" ;;
-    n) run_namcap=true; makepkg_args+=(-i) ;;
-    T) temp_chroot=true; copy+="-$$" ;;
-    h|*) usage ;;
-    esac
-done
-
-[[ ! -f PKGBUILD && -z "${install_pkgs[*]}" ]] && die 'This must be run in a directory containing a PKGBUILD.'
-
-check_root "$0" "${orig_argv[@]}"
-
-# Canonicalize chrootdir, getting rid of trailing /
-chrootdir=$(readlink -e "$passeddir")
-[[ ! -d $chrootdir ]] && die "No chroot dir defined, or invalid path '%s'" "$passeddir"
-[[ ! -d $chrootdir/root ]] && die "Missing chroot dir root directory. Try using: mkchroot %s/root base-devel" "$chrootdir"
-
-# Detect chrootdir filesystem type
-chroottype=$(stat -f -c %T "$chrootdir")
-
-if [[ ${copy:0:1} = / ]]; then
-    copydir=$copy
-else
-    copydir="$chrootdir/$copy"
-fi
-
-# Pass all arguments after -- right to makepkg
-makepkg_args+=("${@:$OPTIND}")
-
-# See if -R was passed to makepkg
-for arg in "${@:OPTIND}"; do
-    case ${arg%%=*} in
-    -*R*|--repackage)
-        repack=true
-        break 2
-    ;;
-    esac
-done
-
-load_user_info
-
-# {{{ functions
-
-create_chroot() {
-    # Lock the chroot we want to use. We'll keep this lock until we exit.
-    lock 9 "$copydir.lock" "Locking chroot copy [$copy]"
-
-    if [[ ! -d $copydir ]] || $clean_first; then
-        # Get a read lock on the root chroot to make
-        # sure we don't clone a half-updated chroot
-        slock 8 "$chrootdir/root.lock" "Locking clean chroot"
-
-        stat_busy "Creating clean working copy [$copy]"
-        if is_btrfs "$chrootdir" && ! mountpoint -q "$copydir"; then
-            subvolume_delete_recursive "$copydir" ||
-                die "Unable to delete subvolume %s" "$copydir"
-            btrfs subvolume snapshot "$chrootdir/root" "$copydir" >/dev/null ||
-                die "Unable to create subvolume %s" "$copydir"
-        else
-            mkdir -p "$copydir"
-            rsync -a --delete -q -W -x "$chrootdir/root/" "$copydir"
-        fi
-        stat_done
-
-        # Drop the read lock again
-        exec 8>&-
+sync_chroot() {
+    local chrootdir=$1
+    local copy=$2
+    local copydir=''
+    if [[ ${copy:0:1} = / ]]; then
+        copydir=$copy
+    else
+        copydir="$chrootdir/$copy"
     fi
+
+    if [[ "$chrootdir/root" -ef "$copydir" ]]; then
+        error 'Cannot sync copy with itself: %s' "$copydir"
+        return 1
+    fi
+
+    # Get a read lock on the root chroot to make
+    # sure we don't clone a half-updated chroot
+    slock 8 "$chrootdir/root.lock" \
+        "Locking clean chroot [%s]" "$chrootdir/root"
+
+    stat_busy "Synchronizing chroot copy [%s] -> [%s]" "$chrootdir/root" "$copydir"
+    if is_btrfs "$chrootdir" && ! mountpoint -q "$copydir"; then
+        subvolume_delete_recursive "$copydir" ||
+            die "Unable to delete subvolume %s" "$copydir"
+        btrfs subvolume snapshot "$chrootdir/root" "$copydir" >/dev/null ||
+            die "Unable to create subvolume %s" "$copydir"
+    else
+        mkdir -p "$copydir"
+        rsync -a --delete -q -W -x "$chrootdir/root/" "$copydir"
+    fi
+    stat_done
+
+    # Drop the read lock again
+    lock_close 8
 
     # Update mtime
     touch "$copydir"
 }
 
-clean_temporary() {
-    stat_busy "Removing temporary copy [$copy]"
+# Usage: delete_chroot $copydir [$copy]
+delete_chroot() {
+    local copydir=$1
+    local copy=${1:-$2}
+
+    stat_busy "Removing chroot copy [%s]" "$copy"
     if is_btrfs "$chrootdir" && ! mountpoint -q "$copydir"; then
-        btrfs subvolume delete "$copydir" >/dev/null ||
+        subvolume_delete_recursive "$copydir" ||
             die "Unable to delete subvolume %s" "$copydir"
     else
         # avoid change of filesystem in case of an umount failure
@@ -163,24 +140,35 @@ clean_temporary() {
     stat_done
 }
 
+# Usage: install_packages $copydir $pkgs...
 install_packages() {
+    local copydir=$1
+    local install_pkgs=("${@:2}")
+
     local -a pkgnames
     local ret
 
     pkgnames=("${install_pkgs[@]##*/}")
 
     cp -- "${install_pkgs[@]}" "$copydir/root/"
-
-    chroot-run "$copydir" \
-            pacman -U --noconfirm -- "${pkgnames[@]/#//root/}"
+    chroot-run -r "${bindmounts_ro[*]}" -w "${bindmounts_rw[*]}" "$copydir" \
+        pacman -U --noconfirm -- "${pkgnames[@]/#//root/}"
     ret=$?
     rm -- "${pkgnames[@]/#/$copydir/root/}"
 
-    # If there is no PKGBUILD we are done
-    [[ -f PKGBUILD ]] || exit $ret
+    return $ret
 }
 
+# Usage: prepare_chroot $copydir $HOME $repack $run_namcap
+# Globals:
+#  - MAKEFLAGS
+#  - PACKAGER
 prepare_chroot() {
+    local copydir=$1
+    local USER_HOME=$2
+    local repack=$3
+    local run_namcap=$4
+
     $repack || rm -rf "$copydir/build"
 
     local builduser_uid="${SUDO_UID:-$UID}"
@@ -204,7 +192,7 @@ prepare_chroot() {
 
     sed -e '/^MAKEFLAGS=/d' -e '/^PACKAGER=/d' -i "$copydir/etc/makepkg.conf"
     for x in BUILDDIR=/build PKGDEST=/pkgdest SRCPKGDEST=/srcpkgdest SRCDEST=/srcdest LOGDEST=/logdest \
-        "MAKEFLAGS='$MAKEFLAGS'" "PACKAGER='$PACKAGER'"
+        "MAKEFLAGS='${MAKEFLAGS:-}'" "PACKAGER='${PACKAGER:-}'"
     do
         grep -q "^$x" "$copydir/etc/makepkg.conf" && continue
         echo "$x" >>"$copydir/etc/makepkg.conf"
@@ -220,9 +208,7 @@ EOF
     {
         printf '#!/bin/bash\n'
         declare -f _chrootbuild
-        printf '_chrootbuild'
-        printf ' %q' "${makepkg_args[@]}"
-        printf ' || exit\n'
+        printf '_chrootbuild "$@" || exit\n'
 
         if $run_namcap; then
             declare -f _chrootnamcap
@@ -236,9 +222,6 @@ EOF
 # so no global variables
 _chrootbuild() {
     . /etc/profile
-#     export HOME=/build
-#     cd /startdir
-#     sudo -u builduser makepkg "$@"
     sudo -iu builduser bash -c 'cd /startdir; makepkg "$@"' -bash "$@"
 }
 
@@ -250,37 +233,52 @@ _chrootnamcap() {
     done
 }
 
+# Usage: download_sources $copydir $src_owner
+# Globals:
+#  - SRCDEST
+#  - USER
 download_sources() {
+    local copydir=$1
+    local src_owner=$2
+
     local builddir="$(mktemp -d)"
     chmod 1777 "$builddir"
 
     # Ensure sources are downloaded
-    if [[ -n $SUDO_USER ]]; then
-        sudo -u $SUDO_USER env SRCDEST="$SRCDEST" BUILDDIR="$builddir" \
+    makepkg_user=${makepkg_user:-$SUDO_USER}
+    if [[ -n $makepkg_user ]]; then
+        sudo -u "$makepkg_user" env SRCDEST="$SRCDEST" BUILDDIR="$builddir" \
             makepkg --config="$copydir/etc/makepkg.conf" --verifysource -o
     else
-        ( export SRCDEST BUILDDIR="$builddir"
-            makepkg --asroot --config="$copydir/etc/makepkg.conf" --verifysource -o
-        )
+        error "Running makepkg as root is not allowed."
+        exit 1
     fi
     (( $? != 0 )) && die "Could not download sources."
 
     # Clean up garbage from verifysource
-    rm -rf $builddir
+    rm -rf "$builddir"
 }
 
+# Usage: move_products $copydir $owner
+# Globals:
+#  - PKGDEST
+#  - LOGDEST
 move_products() {
+    local copydir=$1
+    local src_owner=$2
+
+    local pkgfile
     for pkgfile in "$copydir"/pkgdest/*; do
         chown "$src_owner" "$pkgfile"
         mv "$pkgfile" "$PKGDEST"
 
         # Fix broken symlink because of temporary chroot PKGDEST /pkgdest
         if [[ "$PWD" != "$PKGDEST" && -L "$PWD/${pkgfile##*/}" ]]; then
-            rm "$PWD/${pkgfile##*/}"
             ln -sf "$PKGDEST/${pkgfile##*/}"
         fi
     done
 
+    local l
     for l in "$copydir"/logdest/*; do
         [[ $l == */logpipe.* ]] && continue
         chown "$src_owner" "$l"
@@ -294,49 +292,112 @@ move_products() {
 }
 # }}}
 
-umask 0022
+orig_argv=("$0" "$@")
 
-load_vars "$USER_HOME/.makepkg.conf" || load_vars /etc/makepkg.conf
+main() {
+    init_variables
 
-# Use PKGBUILD directory if these don't exist
-[[ -d $PKGDEST ]]    || PKGDEST=$PWD
-[[ -d $SRCDEST ]]    || SRCDEST=$PWD
-[[ -d $SRCPKGDEST ]] || SRCPKGDEST=$PWD
-[[ -d $LOGDEST ]]    || LOGDEST=$PWD
+    local opts='hcur:I:l:nTD:d:U:'
 
-create_chroot
+    while getopts ${opts} arg; do
+        case "$arg" in
+            c) clean_first=true ;;
+            D) bindmounts_ro+=("$OPTARG") ;;
+			d) bindmounts_rw+=("$OPTARG") ;;
+            u) update_first=true ;;
+            r) passeddir="$OPTARG" ;;
+            I) install_pkgs+=("$OPTARG") ;;
+            l) copy="$OPTARG" ;;
+            n) run_namcap=true; makepkg_args+=(-i) ;;
+            T) temp_chroot=true; copy+="-$$" ;;
+            U) makepkg_user="$OPTARG" ;;
+            h|*) usage ;;
+        esac
+    done
 
-$update_first && chroot-run \
-        -r "${mountargs_ro}" \
-        -w "${mountargs_rw}" \
-        "$copydir" \
+    [[ ! -f PKGBUILD && -z "${install_pkgs[*]}" ]] && die 'This must be run in a directory containing a PKGBUILD.'
+    [[ -n $makepkg_user && -z $(id -u "$makepkg_user") ]] && die 'Invalid makepkg user.'
+
+    check_root
+
+    # Canonicalize chrootdir, getting rid of trailing /
+    chrootdir=$(readlink -e "$passeddir")
+    [[ ! -d $chrootdir ]] && die "No chroot dir defined, or invalid path '%s'" "$passeddir"
+    [[ ! -d $chrootdir/root ]] && die "Missing chroot dir root directory. Try using: mkarchroot %s/root base-devel" "$chrootdir"
+
+    if [[ ${copy:0:1} = / ]]; then
+        copydir=$copy
+    else
+        copydir="$chrootdir/$copy"
+    fi
+
+    # Pass all arguments after -- right to makepkg
+    makepkg_args+=("${@:$OPTIND}")
+
+    # See if -R was passed to makepkg
+    for arg in "${@:OPTIND}"; do
+        case ${arg%%=*} in
+            -*R*|--repackage)
+                repack=true
+                break 2
+                ;;
+        esac
+    done
+
+    load_user_info
+
+    umask 0022
+
+    load_vars "${XDG_CONFIG_HOME:-$USER_HOME/.config}/pacman/makepkg.conf" || load_vars "$USER_HOME/.makepkg.conf"
+    load_vars /etc/makepkg.conf
+
+    # Use PKGBUILD directory if these don't exist
+    [[ -d $PKGDEST ]]    || PKGDEST=$PWD
+    [[ -d $SRCDEST ]]    || SRCDEST=$PWD
+    [[ -d $SRCPKGDEST ]] || SRCPKGDEST=$PWD
+    [[ -d $LOGDEST ]]    || LOGDEST=$PWD
+
+    # Lock the chroot we want to use. We'll keep this lock until we exit.
+    lock 9 "$copydir.lock" "Locking chroot copy [%s]" "$copy"
+
+    if [[ ! -d $copydir ]] || $clean_first; then
+        sync_chroot "$chrootdir" "$copy"
+    fi
+
+    $update_first && chroot-run -r "${bindmounts_ro[*]}" -w "${bindmounts_rw[*]}" "$copydir" \
         pacman -Syu --noconfirm
 
-[[ -n ${install_pkgs[*]} ]] && install_packages
-
-download_sources
-
-prepare_chroot
-
-mountargs_rw="${PWD}:/startdir,${SRCDEST}:/srcdest"
-
-if chroot-run -r "${mountargs_ro}" \
-        -w "${mountargs_rw}" \
-        "$copydir" \
-        /chrootbuild; then
-    move_products
-else
-    (( ret += 1 ))
-fi
-
-$temp_chroot && clean_temporary
-
-if (( ret != 0 )); then
-    if $temp_chroot; then
-        die "Build failed"
-    else
-        die "Build failed, check %s/build" "$copydir"
+    if [[ -n ${install_pkgs[*]:-} ]]; then
+        install_packages "$copydir" "${install_pkgs[@]}"
+        ret=$?
+        # If there is no PKGBUILD we have done
+        [[ -f PKGBUILD ]] || return $ret
     fi
-else
-    true
-fi
+
+    download_sources "$copydir" "$src_owner"
+
+    prepare_chroot "$copydir" "$USER_HOME" "$repack" "$run_namcap"
+
+    bindmounts_rw+=("${PWD}:/startdir" "${SRCDEST}:/srcdest")
+
+    if chroot-run -r "${bindmounts_ro[*]}" -w "${bindmounts_rw[*]}" "$copydir" \
+        /chrootbuild "${makepkg_args[@]}"; then
+        move_products "$copydir" "$src_owner"
+    else
+        (( ret += 1 ))
+    fi
+
+    $temp_chroot && delete_chroot "$copydir" "$copy"
+
+    if (( ret != 0 )); then
+        if $temp_chroot; then
+            die "Build failed"
+        else
+            die "Build failed, check %s/build" "$copydir"
+        fi
+    else
+        true
+    fi
+}
+
+main "$@"
