improve btrfs handling devtools patches

diff --git a/bin/mkchroot.in b/bin/mkchroot.in
--- a/bin/mkchroot.in
+++ b/bin/mkchroot.in
@@ -81,12 +81,12 @@ umask 0022
 
 lock 9 "${working_dir}.lock" "Locking chroot"
 
-if [[ $(stat -f -c %T "$working_dir") == btrfs ]]; then
-    rmdir "$working_dir"
-    if ! btrfs subvolume create "$working_dir"; then
-        die "Couldn't create subvolume for '%s'" "$working_dir"
-    fi
-    chmod 0755 "$working_dir"
+if is_btrfs "$working_dir"; then
+	rmdir "$working_dir"
+	if ! btrfs subvolume create "$working_dir"; then
+		die "Couldn't create subvolume for '%s'" "$working_dir"
+	fi
+	chmod 0755 "$working_dir"
 fi
 
 # Workaround when creating a chroot in a branch different of the host
