small fixes; add sanity check for pkg or profile dir

diff --git a/bin/mkset.in b/bin/mkset.in
--- a/bin/mkset.in
+++ b/bin/mkset.in
@@ -21,31 +21,46 @@ load_user_info
 load_config "${USER_CONFIG}/manjaro-tools.conf"  
 load_config "${SYSCONFDIR}/manjaro-tools.conf"
 
+write_set(){
+	msg2 "Adding ${1##*/}"
+	echo ${1##*/} >> ${2}/${name}.set || break
+}
+write_set_iso(){
+
+}
+
 create_set(){
-    msg "Creating [${sets_dir_pkg}/${name}.set] ..."
-    if [[ -f ${sets_dir_pkg}/${name}.set ]];then
-	msg2 "Backing up ${sets_dir_pkg}/${name}.set.orig"
-	mv "${sets_dir_pkg}/${name}.set" "${sets_dir_pkg}/${name}.set.orig"
+    msg "Creating [$1/${name}.set] ..."
+    if [[ -f $1/${name}.set ]];then
+	msg2 "Backing up $1/${name}.set.orig"
+	mv "$1/${name}.set" "$1/${name}.set.orig"
     fi
     local list=$(find * -maxdepth 0 -type d | sort)
     for item in ${list[@]};do
 	cd $item
-	if [[ -f PKGBUILD ]];then
-	    msg2 "Adding ${item##*/}"
-	    echo ${item##*/} >> ${sets_dir_pkg}/${name}.set || break
-	fi
+	    if ${iso_mode}; then
+		
+		if [[ -f displaymanager ]] && [[ -f initsys ]];then
+		    write_set "$item" "${sets_dir_iso}"
+		fi
+	    else
+		if [[ -f PKGBUILD ]];then
+		    write_set "$item" "${sets_dir_pkg}"
+		fi
+	    fi
 	cd ..
     done
+
 }
 
 remove_set(){
-    msg "Removing [${sets_dir_pkg}/${name}.set] ..."
-    rm ${sets_dir_pkg}/${name}.set
+    msg "Removing [$1/${name}.set] ..."
+    rm $1/${name}.set
 }
 
 show_set(){
-    local list=$(cat ${sets_dir_pkg}/${name}.set)
-    msg "Content of [${sets_dir_pkg}/${name}.set] ..."
+    local list=$(cat $1/${name}.set)
+    msg "Content of [$1/${name}.set] ..."
     for item in ${list[@]}; do
 	msg2 "$item"
     done
@@ -56,17 +71,19 @@ create=false
 remove=false
 display=false
 name='default'
+iso_mode=false
 
 usage() {
     echo "Usage: ${0##*/} [options]"
     echo "    -c <name>   Create set"
     echo "    -r <name>   Remove set"
     echo "    -d <name>   Display set"
-    echo "    -q          Show sets"
+    echo "    -i          Iso mode"
+    echo "    -q          Query sets"
     echo '    -h          This help'
     echo ''
     echo ''
-    exit 1
+    exit $1
 }
 
 orig_argv=("$@")
@@ -78,14 +95,17 @@ while getopts "${opts}" arg; do
 	c) name="$OPTARG"; create=true ;;
 	r) name="$OPTARG"; remove=true ;;
 	q) query=true ;;
+	i) iso_mode=true ;;
 	d) name="$OPTARG"; display=true;;
-	h) usage ;;
+	h|?) usage 0 ;;
+        *) echo "invalid argument '${arg}'"; usage 1 ;;
     esac
 done
 
 shift $(($OPTIND - 1))
 
 sets_dir_pkg="${sets_dir}/pkg"
+sets_dir_iso="${sets_dir}/iso"
 
 check_root "$0" "${orig_argv[@]}"
 
