initcpio: add persistence option; aufs probably doesn't work(wip)

diff --git a/initcpio/hooks/miso_overlayfs b/initcpio/hooks/miso_overlayfs
--- a/initcpio/hooks/miso_overlayfs
+++ b/initcpio/hooks/miso_overlayfs
@@ -1,248 +1,173 @@
-# kernel_cmdline <param> <default>
-# Looks for a parameter on the kernel's boot-time command line.
-#
-# returns: 0 if param was found. Also prints its value if it was a K=V param.
-#          1 if it was not. Also prints value passed as <default>
-#
+# args: source, newroot, mountpoint
+_mnt_dmsnapshot() {
+    local img="${1}"
+    local newroot="${2}"
+    local mnt="${3}"
+    local img_fullname="${img##*/}";
+    local img_name="${img_fullname%%.*}"
+    local dm_snap_name="${dm_snap_prefix}_${img_name}"
+    local ro_dev ro_dev_size rw_dev
 
-kernel_cmdline ()
-{
-    for param in $(/bin/cat /proc/cmdline); do
-        case "${param}" in
-            $1=*) echo "${param##*=}"; return 0 ;;
-            $1) return 0 ;;
-            *) continue ;;
-        esac
-    done
-    [ -n "${2}" ] && echo "${2}"
-    return 1
+    ro_dev=$(losetup --find --show --read-only "${img}")
+    echo ${ro_dev} >> /run/miso/used_block_devices
+    ro_dev_size=$(blockdev --getsz ${ro_dev})
+
+    if [[ "${cow_persistent}" == "P" ]]; then
+        if [[ -f "/run/miso/cowspace/${cow_directory}/${img_name}.cow" ]]; then
+            msg ":: Found '/run/miso/cowspace/${cow_directory}/${img_name}.cow', using as persistent."
+        else
+            msg ":: Creating '/run/miso/cowspace/${cow_directory}/${img_name}.cow' as persistent."
+            truncate -s "${cow_spacesize}" "/run/miso/cowspace/${cow_directory}/${img_name}.cow"
+        fi
+    else
+        if [[ -f "/run/miso/cowspace/${cow_directory}/${img_name}.cow" ]]; then
+            msg ":: Found '/run/miso/cowspace/${cow_directory}/${img_name}.cow' but non-persistent requested, removing."
+            rm -f "/run/miso/cowspace/${cow_directory}/${img_name}.cow"
+        fi
+        msg ":: Creating '/run/miso/cowspace/${cow_directory}/${img_name}.cow' as non-persistent."
+        truncate -s "${cow_spacesize}" "/run/miso/cowspace/${cow_directory}/${img_name}.cow"
+    fi
+
+    rw_dev=$(losetup --find --show "/run/miso/cowspace/${cow_directory}/${img_name}.cow")
+    echo ${rw_dev} >> /run/miso/used_block_devices
+
+    dmsetup create ${dm_snap_name} --table "0 ${ro_dev_size} snapshot ${ro_dev} ${rw_dev} ${cow_persistent} ${cow_chunksize}"
+
+    _mnt_dev "/dev/mapper/${dm_snap_name}" "${newroot}${mnt}" "-w" "defaults"
+    echo $(readlink -f /dev/mapper/${dm_snap_name}) >> /run/miso/used_block_devices
 }
 
-# 1$ : kernel argument to check
-overlay_arg_available() {
-	for arg in $(echo "$(kernel_cmdline overlay)" | /bin/sed 's/,/ /g')
-	do
-		[ "${arg}" == "$1" ] && return 0
-	done
-
-	return 1
-}
-
-# args: source, mountpoint
-_mnt_bind() {
-    local src="${1}"
-    local mnt="${2}"
-    msg "::: Binding ${src} to ${mnt}"
-    mkdir -p "${mnt}"
-    /bin/mount -o bind "${src}" "${mnt}"
+# args: source, newroot, mountpoint
+_mnt_overlayfs() {
+    local lower_dir="${1}"
+    local newroot="${2}"
+    local mnt="${3}"
+    local work_dir=/run/miso/cowspace/${cow_directory}/workdir
+    local upper_dir=/run/miso/cowspace/${cow_directory}/upperdir
+    mkdir -p ${upper_dir} ${work_dir}
+    mount -t overlay misofs -o lowerdir=${lower_dir},upperdir=${upper_dir},workdir=${work_dir} "${newroot}${mnt}"
 }
 
 # args: /path/to/image_file, mountpoint
-_mnt_squashfs() {
+_mnt_sfs() {
     local img="${1}"
     local mnt="${2}"
-    local img_fullname="${img##*/}";
-    local img_name="${img_fullname%.*}"
-    local tmp_mnt="/ro_branch/${img_name}"
+    local img_fullname="${img##*/}"
+    local sfs_dev
 
-    if [ "${copytoram}" = "y" ]; then
+    if [[ "${copytoram}" == "y" ]]; then
         msg -n ":: Copying squashfs image to RAM..."
-        /bin/cp "${img}" "/copytoram/${img_fullname}"
-        if [ $? -ne 0 ]; then
-            echo ">> ERROR: while copy ${img} to /copytoram/${img_fullname}"
+        if ! cp "${img}" "/run/miso/copytoram/${img_fullname}" ; then
+            echo "ERROR: while copy '${img}' to '/run/miso/copytoram/${img_fullname}'"
             launch_interactive_shell
         fi
-        img="/copytoram/${img_fullname}"
+        img="/run/miso/copytoram/${img_fullname}"
         msg "done."
     fi
+    sfs_dev=$(losetup --find --show --read-only "${img}")
+    echo ${sfs_dev} >> /run/miso/used_block_devices
+    _mnt_dev "${sfs_dev}" "${mnt}" "-r" "defaults"
+}
 
-    mkdir -p "${tmp_mnt}"
-    /bin/mount -r -t squashfs "${img}" "${tmp_mnt}"
-    if [ $? -ne 0 ]; then
-        echo ">> ERROR: while mounting ${img} to ${tmp_mnt}"
+# args: device, mountpoint, flags, opts
+_mnt_dev() {
+    local dev="${1}"
+    local mnt="${2}"
+    local flg="${3}"
+    local opts="${4}"
+
+    mkdir -p "${mnt}"
+
+    msg ":: Mounting '${dev}' to '${mnt}'"
+
+    while ! poll_device "${dev}" 30; do
+        echo "ERROR: '${dev}' device did not show up after 30 seconds..."
+        echo "   Falling back to interactive prompt"
+        echo "   You can try to fix the problem manually, log out when you are finished"
         launch_interactive_shell
-    fi
+    done
 
-    if [ "/${mnt#/*/}" = "/" ]; then
-        overlayfs="${overlayfs}:${tmp_mnt}"
+    if mount -o "${opts}" "${flg}" "${dev}" "${mnt}"; then
+        msg ":: Device '${dev}' mounted successfully."
     else
-        _mnt_bind "${tmp_mnt}" "${mnt}"
+        echo "ERROR; Failed to mount '${dev}'"
+        echo "   Falling back to interactive prompt"
+        echo "   You can try to fix the problem manually, log out when you are finished"
+        launch_interactive_shell
     fi
 }
 
 run_hook() {
-    modprobe loop
-    if [ "x${arch}" = "x" ]; then
-        arch="$(uname -m)"
-    fi
+    [[ -z "${arch}" ]] && arch="$(uname -m)"
+    [[ -z "${copytoram_size}" ]] && copytoram_size="75%"
+    [[ -z "${misobasedir}" ]] && misobasedir="manjaro"
 
-    if [ "x${rw_branch_size}" = "x" ]; then
-        rw_branch_size="75%"
-    fi
+    [[ -z "${dm_snap_prefix}" ]] && dm_snap_prefix="arch"
+    [[ -z "${misodevice}" ]] && misodevice="/dev/disk/by-label/${misolabel}"
+    [[ -z "${cow_spacesize}" ]] && cow_spacesize="256M"
 
-    if [ "x${copytoram_size}" = "x" ]; then
-        copytoram_size="75%"
-    fi
-
-    if [ "x${misobasedir}" = "x" ]; then
-        misobasedir="manjaro"
-    fi
-
-    if [ "x${isomounts}" != "x" ]; then
-        isomounts="/bootmnt/${isomounts}"
+    if [[ -n "${cow_label}" ]]; then
+        cow_device="/dev/disk/by-label/${cow_label}"
+        [[ -z "${cow_persistent}" ]] && cow_persistent="P"
+    elif [[ -n "${cow_device}" ]]; then
+        [[ -z "${cow_persistent}" ]] && cow_persistent="P"
     else
-        isomounts="/bootmnt/${misobasedir}/isomounts"
+        cow_persistent="N"
     fi
+
+    [[ -z "${cow_flags}" ]] && cow_flags="defaults"
+    [[ -z "${cow_directory}" ]] && cow_directory="persistent_${misolabel}/${arch}"
+    [[ -z "${cow_chunksize}" ]] && cow_chunksize="8"
 
     # set mount handler for miso
     mount_handler="miso_mount_handler"
 }
 
-testdevice() {
-    fstype=$( blkid -s TYPE -o value ${MDEV} )
-    mount -r -t ${fstype} -o noatime "${MDEV}" "/bootmnt" >/dev/null 2>/dev/null
-    if [ $? -eq 0 ]; then
-        if [ -f "/bootmnt/.miso" ]; then
-            msg "::: INFO: miso system at ${MDEV}"
-            found="yes"
-        else
-            /bin/umount "/bootmnt/" 2>/dev/null
-            msg  "::: INFO: No miso system at ${MDEV}"
-            MDEV=""
-        fi
-    else
-        msg ">> ERROR: Couldn't mount ${MDEV}"
-        MDEV=""
-    fi
-}
-
-probedevice() {
-
-# Loop device test every second up to some limit
-    if [ "x${usbdelay}" != "x" ]; then
-        waittime=${usbdelay}
-    else
-        waittime=35
-    fi
-    waitcount=0
-    while [ ${waittime} -ne ${waitcount} ]; do
-        # first we look for root, e.g. /dev/sda1 to see if .miso will be found
-        if [ "x${root}" != "x" ]; then
-            [ ${waitcount} -eq 0 ] && msg ":: Looking for ${root}"
-            if [ -e ${root} ]; then
-                MDEV=${root}
-                testdevice
-            fi
-        fi
-
-        # if still not found, we will look for misolabel
-        if [ "x${misolabel}" != "x" ]; then
-            [ ${waitcount} -eq 0 ] && msg ":: Looking for LABEL ${misolabel}"
-            MDEV=$( blkid -L ${misolabel} )
-            if [ "x${MDEV}" != "x" ]; then
-                testdevice
-            else
-                msg "::: INFO: LABEL ${misolabel} is not valid!"
-                misolabel=""
-            fi
-        fi
-
-        # still nothing found, we will look for boot device
-        [ ${waitcount} -eq 0 ] && msg ":: Looking for boot device"
-        if [ "x${nocd}" = "x" ]; then
-            # Look for CD
-            cdroms=$( /bin/cat /proc/sys/dev/cdrom/info | { while read a b c; do
-                    if [ "${a}" = "drive" -a "${b}" = "name:" ]; then
-                        echo "${c}"
-                        break
-                    fi
-                done
-            } )
-            for i in ${cdroms}; do
-                MDEV=/dev/${i}
-                testdevice
-                if [ "x${MDEV}" != "x" ]; then
-                    break
-                fi
-            done
-        fi
-
-        # Test partitions
-        if [ "x${MDEV}" = "x" ]; then
-            for d in /dev/sd[a-z][0-9]*; do
-                MDEV=${d}
-                testdevice
-                if [ "x${MDEV}" != "x" ]; then
-                    break
-                fi
-            done
-        fi
-
-        [ "x${MDEV}" != "x" ] && break
-
-        /bin/sleep 1
-        waitcount=$(( ${waitcount} + 1 ))
-    done
-}
-
+# This function is called normally from init script, but it can be called
+# as chain from other mount handlers.
+# args: /path/to/newroot
 miso_mount_handler() {
     local newroot="${1}"
-    local found
-    local overlayfs
 
-    # Probe all devices
-    probedevice
-
-    if [ -z "${found}" ]; then
-        echo ">> ERROR: unable to find boot device"
-        echo "   Falling back to interactive prompt"
-        echo "   You can try to fix the problem manually, log out when you are finished"
-        launch_interactive_shell
+    if ! mountpoint -q "/run/miso/bootmnt"; then
+        _mnt_dev "${misodevice}" "/run/miso/bootmnt" "-r" "defaults"
+        if [[ "${copytoram}" != "y" ]]; then
+            echo $(readlink -f ${misodevice}) >> /run/miso/used_block_devices
+        fi
     fi
 
-    if [ "${copytoram}" = "y" ]; then
-        msg -n ":: Mounting /copytoram (tmpfs) filesystem, size=${copytoram_size}..."
-        mount -t tmpfs -o "size=${copytoram_size}",mode=0755 copytoram /copytoram
-        msg "done."
+    if [[ "${copytoram}" == "y" ]]; then
+        msg ":: Mounting /run/miso/copytoram (tmpfs) filesystem, size=${copytoram_size}"
+        mkdir -p /run/miso/copytoram
+        mount -t tmpfs -o "size=${copytoram_size}",mode=0755 copytoram /run/miso/copytoram
     fi
 
-    msg -n ":: Mounting rw_branch (tmpfs) filesystem, size=${rw_branch_size}..."
-    mount -t tmpfs -o "size=${rw_branch_size}",mode=0755 rw_branch /rw_branch
-    msg "done."
-
-    msg ":: Mounting images"
-    while read img imgarch mountpoint type kernelarg; do
-        # check if this line is a comment (starts with #)
-        [ "${img#"#"}" != "${img}" ] && continue
-
-        [ "$imgarch" != "$arch" ] && continue
-
-        [ ! -r "/bootmnt/${misobasedir}/${img}" ] && continue
-
-        # check if the overlay should be loaded
-        overlay_arg_available "$kernelarg"
-
-
-        if [ $? == 1 ] && [ "$kernelarg" != "" ]; then
-	        continue
-        fi
-
-        if [ "${type}" = "bind" ]; then
-            _mnt_bind "/bootmnt/${misobasedir}/${img}" "${newroot}${mountpoint}"
-        elif [ "${type}" = "squashfs" ]; then
-            _mnt_squashfs "/bootmnt/${misobasedir}/${img}" "${newroot}${mountpoint}"
-        fi
-    done < "${isomounts}"
-
-    msg "Mounting ${overlayfs:1}"
-    mkdir -p "/rw_branch/upper"
-    mkdir -p "/rw_branch/work"
-    mount -t overlay overlay -olowerdir="${overlayfs:1}",upperdir="/rw_branch/upper",workdir="/rw_branch/work" "${newroot}/"
-
-    if [ "${copytoram}" = "y" ]; then
-        /bin/umount -d /bootmnt
+    if [[ -n "${cow_device}" ]]; then
+        _mnt_dev "${cow_device}" "/run/miso/cowspace" "-r" "${cow_flags}"
+        echo $(readlink -f ${cow_device}) >> /run/miso/used_block_devices
+        mount -o remount,rw "/run/miso/cowspace"
     else
-        _mnt_bind /bootmnt "${newroot}/bootmnt"
+        msg ":: Mounting /run/miso/cowspace (tmpfs) filesystem, size=${cow_spacesize}..."
+        mkdir -p /run/miso/cowspace
+        mount -t tmpfs -o "size=${cow_spacesize}",mode=0755 cowspace /run/miso/cowspace
+    fi
+    mkdir -p -m 0700 "/run/miso/cowspace/${cow_directory}"
+
+    local _src=/run/miso/bootmnt/${misobasedir}/${arch}
+
+    for fs in livefs mhwdfs desktopfs rootfs cowfs;do
+        if [[ -f "${_src}/${fs}.sfs" ]]; then
+            _mnt_sfs "${_src}/${fs}.sfs" "/run/miso/sfs/${fs}"
+            if [[ -f "/run/miso/sfs/${fs}/${fs}.img" ]]; then
+                _mnt_dmsnapshot "/run/miso/sfs/${fs}/${fs}.img" "${newroot}" "/"
+            else
+                _mnt_overlayfs "/run/miso/sfs/${fs}" "${newroot}" "/"
+            fi
+        fi
+    done
+
+    if [[ "${copytoram}" == "y" ]]; then
+        umount -d /run/miso/bootmnt
     fi
 }
 
diff --git a/initcpio/hooks/miso_pxe_common b/initcpio/hooks/miso_pxe_common
--- a/initcpio/hooks/miso_pxe_common
+++ b/initcpio/hooks/miso_pxe_common
@@ -1,7 +1,8 @@
 # vim: set ft=sh:
 
 run_hook () {
-    local i net_mac bootif_mac bootif_dev
+    # Do *not* declare 'bootif_dev' local! We need it in run_latehook().
+    local i net_mac bootif_mac
     # These variables will be parsed from /tmp/net-*.conf generated by ipconfig
     local DEVICE
     local IPV4ADDR IPV4BROADCAST IPV4NETMASK IPV4GATEWAY IPV4DNS0 IPV4DNS1
@@ -25,7 +26,12 @@ run_hook () {
         fi
 
         # setup network and save some values
-        ipconfig "ip=${ip}"
+        if ! ipconfig "ip=${ip}"; then
+                echo "ERROR; Failed to configure network"
+                echo "   Falling back to interactive prompt"
+                echo "   You can try to fix the problem manually, log out when you are finished"
+                launch_interactive_shell
+        fi
 
         . /tmp/net-*.conf
 
@@ -42,9 +48,16 @@ run_hook () {
 }
 
 run_latehook () {
-    [[ -z "${copy_resolvconf}" ]] && copy_resolvconf="y"
+    if [[ -n "${ip}" ]]; then
+        [[ -z "${copy_resolvconf}" ]] && copy_resolvconf="y"
 
-    if [[ "${copy_resolvconf}" != "n" && -f /etc/resolv.conf ]]; then
-        cp /etc/resolv.conf /new_root/etc/resolv.conf
+        if [[ "${copytoram}" == "y" ]]; then
+            if [[ -n "${bootif_dev}" ]]; then
+                ip addr flush dev "${bootif_dev}"
+                ip link set "${bootif_dev}" down
+            fi
+        elif [[ "${copy_resolvconf}" != "n" && -f /etc/resolv.conf ]]; then
+            cp /etc/resolv.conf /new_root/etc/resolv.conf
+        fi
     fi
 }
